ci:
  config:
    trunk_branch: main
    triggers:
      - cmd/**
      - internal/**
      - e2e/**
      - go.mod
      - go.sum
    cli_version: v0.1.0
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    validate:
      workflow: .github/workflows/validate.yaml
    builds:
      - name: cli
        workflow: .github/workflows/build-cli.yaml
        triggers: []
    changelog:
      contributors: true
  state:
    prerelease:
      sha: bcf97acb61788c882d21c928363f338d6ac7960b
      version: v0.2.0-rc.2
      committed_at: "2026-06-10T06:49:52Z"
      committed_by: joshua-temple
