ci:
  config:
    trunk_branch: main
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    triggers:
      - cmd/**
      - internal/**
      - e2e/**
      - go.mod
      - go.sum
    cli_version: v0.1.0
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    validate:
      workflow: .github/workflows/validate.yaml
    builds:
      - name: cli
        workflow: .github/workflows/build-cli.yaml
        triggers: []
    changelog:
      contributors: true
  state:
    prerelease:
      sha: 8e47e4aeac33fb6baba0b6c9ea3eea19ce3d61b3
      version: v0.3.0-rc.6
      committed_at: "2026-06-21T06:10:44Z"
      committed_by: joshua-temple
