ci:
  config:
    trunk_branch: main
    triggers:
      - cmd/**
      - internal/**
      - e2e/**
      - go.mod
      - go.sum
    cli_version: v0.1.0
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    validate:
      workflow: .github/workflows/validate.yaml
    builds:
      - name: cli
        workflow: .github/workflows/build-cli.yaml
        triggers: []
    changelog:
      contributors: true
  state:
    prerelease:
      sha: a310f7640c246295c9c702415a7ab04ae6f435e9
      version: v0.2.0-rc.9
      committed_at: "2026-06-10T08:40:32Z"
      committed_by: joshua-temple
