#!/usr/bin/env bash
# Update manifest.yaml with deployment information
# Usage: update-manifest.sh --manifest-path <path> --environment <env> --sha <sha> --image-tag <tag> [--version <ver>] [--deployed-by <actor>]
#
# Outputs (2 lines to stdout):
#   1. updated: "true" or "false"
#   2. previous_sha: SHA that was previously deployed (or empty)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/log.sh"
source "$SCRIPT_DIR/lib/yaml.sh"

# Parse arguments
MANIFEST_PATH=""
ENVIRONMENT=""
SHA=""
IMAGE_TAG=""
VERSION=""
DEPLOYED_BY="${GITHUB_ACTOR:-unknown}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --manifest-path)
      MANIFEST_PATH="$2"
      shift 2
      ;;
    --environment)
      ENVIRONMENT="$2"
      shift 2
      ;;
    --sha)
      SHA="$2"
      shift 2
      ;;
    --image-tag)
      IMAGE_TAG="$2"
      shift 2
      ;;
    --version)
      VERSION="$2"
      shift 2
      ;;
    --deployed-by)
      DEPLOYED_BY="$2"
      shift 2
      ;;
    *)
      log_error "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Validate required arguments
if [[ -z "$MANIFEST_PATH" ]]; then
  log_error "Missing required argument: --manifest-path"
  exit 1
fi

if [[ -z "$ENVIRONMENT" ]]; then
  log_error "Missing required argument: --environment"
  exit 1
fi

if [[ -z "$SHA" ]]; then
  log_error "Missing required argument: --sha"
  exit 1
fi

if [[ -z "$IMAGE_TAG" ]]; then
  log_error "Missing required argument: --image-tag"
  exit 1
fi

# Environment validation removed - any environment name is accepted
# Environments are defined in cicd-config.yaml

log_info "Updating manifest: $MANIFEST_PATH for $ENVIRONMENT"

# Create manifest if it doesn't exist
# Only creates a minimal structure - environment must be added dynamically
if [[ ! -f "$MANIFEST_PATH" ]]; then
  log_info "Creating new manifest file"
  cat > "$MANIFEST_PATH" << 'EOF'
# Deployment manifest - tracks what's deployed to each environment
# Auto-generated by CI/CD pipeline

environments: {}
EOF
fi

# Ensure environment structure exists
if ! yq eval ".environments.$ENVIRONMENT" "$MANIFEST_PATH" 2>/dev/null | grep -q "sha"; then
  log_info "Initializing environment: $ENVIRONMENT"
  yq eval -i ".environments.$ENVIRONMENT = {\"sha\": \"\", \"image_tag\": \"\", \"deployed_at\": \"\", \"deployed_by\": \"\"}" "$MANIFEST_PATH"
fi

# Get previous SHA
PREVIOUS_SHA=$(yaml_get "$MANIFEST_PATH" ".environments.$ENVIRONMENT.sha" 2>/dev/null || echo "")
if [[ "$PREVIOUS_SHA" == "null" ]]; then
  PREVIOUS_SHA=""
fi

log_debug "Previous SHA: ${PREVIOUS_SHA:-none}"

# Check if update is needed
CURRENT_SHA=$(yaml_get "$MANIFEST_PATH" ".environments.$ENVIRONMENT.sha" 2>/dev/null || echo "")
CURRENT_IMAGE_TAG=$(yaml_get "$MANIFEST_PATH" ".environments.$ENVIRONMENT.image_tag" 2>/dev/null || echo "")

if [[ "$CURRENT_SHA" == "$SHA" && "$CURRENT_IMAGE_TAG" == "$IMAGE_TAG" ]]; then
  log_info "Manifest already up to date"
  echo "false"
  echo "$PREVIOUS_SHA"
  exit 0
fi

# Update manifest
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

log_debug "Setting SHA: $SHA"
yaml_set "$MANIFEST_PATH" ".environments.$ENVIRONMENT.sha" "$SHA"

log_debug "Setting image_tag: $IMAGE_TAG"
yaml_set "$MANIFEST_PATH" ".environments.$ENVIRONMENT.image_tag" "$IMAGE_TAG"

log_debug "Setting deployed_at: $TIMESTAMP"
yaml_set "$MANIFEST_PATH" ".environments.$ENVIRONMENT.deployed_at" "$TIMESTAMP"

log_debug "Setting deployed_by: $DEPLOYED_BY"
yaml_set "$MANIFEST_PATH" ".environments.$ENVIRONMENT.deployed_by" "$DEPLOYED_BY"

# Set version if provided (typically only for prod/final environment)
if [[ -n "$VERSION" ]]; then
  log_debug "Setting version: $VERSION"
  yaml_set "$MANIFEST_PATH" ".environments.$ENVIRONMENT.version" "$VERSION"
fi

log_success "Manifest updated for $ENVIRONMENT"

# Output results
echo "true"
echo "$PREVIOUS_SHA"
