package verify

import (
	"github.com/spf13/cobra"

	"github.com/stablekernel/cascade/internal/config"
)

// NewCommand creates the verify command, a read-only drift check that compares
// committed workflow and action files against what the manifest would generate.
func NewCommand() *cobra.Command {
	var o Options

	cmd := &cobra.Command{
		Use:   "verify",
		Short: "Check committed workflows against the manifest for drift",
		Long: `Compare the committed GitHub Actions workflow and action files against what
the manifest would currently generate, without writing anything.

verify reports drift when a file the manifest would generate is missing on disk
or its committed bytes differ from the generated bytes. It exits non-zero on
drift and zero when the committed files are in sync, so it can replace a
hand-rolled "regenerate and git diff" CI step with a single command. A missing
or invalid manifest is reported as an operational failure, distinct from drift.

verify is read-only: it never writes files, runs git, or modifies the repo.`,
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			return Run(o, cmd.OutOrStdout(), cmd.ErrOrStderr())
		},
	}

	cmd.Flags().StringVarP(&o.ConfigPath, "config", "c", "", "Path to config file (default: auto-detect .github/manifest.yaml)")
	cmd.Flags().StringVar(&o.ManifestKey, "manifest-key", config.DefaultManifestKey, "Key in manifest file containing CI config")
	cmd.Flags().StringVar(&o.ActionFolder, "action-folder", "manage-release", "Folder name for the manage-release composite action")
	cmd.Flags().StringVarP(&o.OutputPath, "output", "o", ".github/workflows/orchestrate.yaml", "Path of the orchestrate workflow")
	cmd.Flags().StringVar(&o.PromoteOutputPath, "promote-output", ".github/workflows/promote.yaml", "Path of the promote workflow")
	cmd.Flags().BoolVarP(&o.Quiet, "quiet", "q", false, "Suppress the per-file report body; only set the exit code")
	cmd.Flags().BoolVar(&o.AllowOrphans, "allow-orphans", false, "Do not report cascade-owned workflow files that are no longer in the plan as drift")

	return cmd
}
