package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stablekernel/cascade/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// mockWorkflowContent returns a minimal workflow YAML that the generator can parse
const mockWorkflowContent = `name: Mock Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    outputs:
      deployed_sha:
        value: ${{ jobs.deploy.outputs.sha }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ github.sha }}
    steps:
      - run: echo "deploying"
`

// checkoutStepBlock returns the slice of the generated workflow content that
// covers the actions/checkout step and its "with:" block, stopping at the next
// "- name:" or "- uses:" step boundary. This lets tests assert on the checkout
// token and fetch-depth in isolation, without false matches from tokens used in
// other steps such as setup-cli.
func checkoutStepBlock(t *testing.T, content string) string {
	t.Helper()
	lines := strings.Split(content, "\n")
	start := -1
	for i, line := range lines {
		if strings.Contains(line, "uses: actions/checkout") {
			start = i
			break
		}
	}
	require.GreaterOrEqual(t, start, 0, "no actions/checkout step found in generated content")
	var sb strings.Builder
	for i := start; i < len(lines); i++ {
		// Stop at the next step boundary (a "- name:" or "- uses:" line that is
		// not the checkout line itself).
		if i > start && (strings.Contains(lines[i], "- name:") || strings.Contains(lines[i], "- uses:")) {
			break
		}
		sb.WriteString(lines[i])
		sb.WriteString("\n")
	}
	return sb.String()
}

// createMockWorkflow creates a mock workflow file in a temp directory
func createMockWorkflow(t *testing.T, baseDir, workflowPath string) {
	t.Helper()
	fullPath := filepath.Join(baseDir, workflowPath)
	err := os.MkdirAll(filepath.Dir(fullPath), 0755)
	require.NoError(t, err)
	err = os.WriteFile(fullPath, []byte(mockWorkflowContent), 0644)
	require.NoError(t, err)
}

// =============================================================================
// Multi-Repo Orchestration Integration Tests
// =============================================================================

// TestExternalUpdateWorkflow_Generation tests that the external-update workflow
// is correctly generated for primary repos that coordinate satellite deploys.
func TestExternalUpdateWorkflow_Generation(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
			{
				Repo: "example/k8s-manifests",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "k8s", Workflow: "example/k8s-manifests/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have workflow header
	assert.Contains(t, content, "# AUTO-GENERATED by cascade")
	assert.Contains(t, content, "name: External Update")

	// Should have workflow_dispatch trigger with inputs for external updates
	assert.Contains(t, content, "workflow_dispatch:")
	assert.Contains(t, content, "inputs:")

	// Should accept deploy info as inputs
	assert.Contains(t, content, "source_repo")
	assert.Contains(t, content, "deploy_name")
	assert.Contains(t, content, "environment")
	assert.Contains(t, content, "sha")

	// Should call the external update CLI command
	assert.Contains(t, content, "cascade external update")
	assert.Contains(t, content, "--source-repo")
	assert.Contains(t, content, "--deploy-name")
	assert.Contains(t, content, "--environment")
	assert.Contains(t, content, "--sha")

	// Should configure a git identity before the verb runs. `cascade external
	// update` commits and pushes the manifest state via git, which aborts on a
	// clean runner with no identity, so the workflow must set one first.
	assert.Contains(t, content, "Configure Git")
	assert.Contains(t, content, "git config user.name")
	assert.Contains(t, content, "git config user.email")
	assert.Less(t, strings.Index(content, "Configure Git"),
		strings.Index(content, "cascade external update"),
		"git identity must be configured before the update verb commits")
}

// TestSatelliteNotifyPrimary_Generation tests that satellite repos generate
// a notify-primary step in the orchestrate finalize job.
func TestSatelliteNotifyPrimary_Generation(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev", "test", "prod"},
		Notify: &config.NotifyConfig{
			Repo:     "example/primary-backend",
			Workflow: ".github/workflows/external-update.yaml",
		},
	}

	gen := NewGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have notify primary step
	assert.Contains(t, content, "Notify Primary")

	// Should dispatch to the primary repo using workflow dispatch
	assert.Contains(t, content, "example/primary-backend")
	assert.Contains(t, content, "createWorkflowDispatch")

	// Should pass deploy info in payload
	assert.Contains(t, content, "source_repo")
	assert.Contains(t, content, "environment")
	assert.Contains(t, content, "sha")
}

// TestPromoteExternalDeploys_Generation tests that promote workflow correctly
// generates external deploy jobs when external deploys are configured.
func TestPromoteExternalDeploys_Generation(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "app", Workflow: ".github/workflows/deploy-app.yaml"},
		},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewPromoteGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have local deploy job
	assert.Contains(t, content, "deploy-app:")
	assert.Contains(t, content, "name: Deploy app")

	// Should have external deploy job
	assert.Contains(t, content, "deploy-cdk:")
	assert.Contains(t, content, "name: Deploy cdk (external)")

	// Should have prod deploy jobs for cascade mode
	assert.Contains(t, content, "deploy-app-prod:")
	assert.Contains(t, content, "deploy-cdk-prod:")

	// External deploy should use cross-repo workflow_call
	assert.Contains(t, content, "example/cdk-infra/.github/workflows/deploy.yaml@main")

	// Should have external_deploys_to_run output
	assert.Contains(t, content, "external_deploys_to_run:")
	assert.Contains(t, content, "steps.preflight.outputs.external_deploys_to_run")

	// Should have rollback jobs for both local and external
	assert.Contains(t, content, "rollback-app:")
	assert.Contains(t, content, "rollback-cdk:")

	// Finalize needs should include external deploy jobs
	assert.Contains(t, content, "deploy-cdk")
	assert.Contains(t, content, "deploy-cdk-prod")
}

// TestExternalDeployStateTracking tests that preflight correctly identifies
// external deploys that need to run based on state differences.
func TestExternalDeployStateTracking(t *testing.T) {
	// This test covers the integration between config and preflight
	cicdFile := &config.CICDFile{
		Config: &config.TrunkConfig{
			Environments: []string{"dev", "test", "prod"},
			Deploys: []config.DeployConfig{
				{Name: "app"},
			},
			External: []config.ExternalRepoConfig{
				{
					Repo: "example/cdk",
					Ref:  "main",
					Deploys: []config.ExternalDeployConfig{
						{Name: "cdk", Workflow: "example/cdk/.github/workflows/deploy.yaml"},
					},
				},
			},
		},
		State: map[string]*config.EnvState{
			"dev": {
				SHA:     "abc123",
				Version: "v1.0.0-rc.0",
				External: map[string]*config.ExternalDeployState{
					"cdk": {SHA: "cdk-sha-123"},
				},
			},
			"test": {
				SHA:     "def456", // Different from dev
				Version: "v0.9.0",
				External: map[string]*config.ExternalDeployState{
					"cdk": {SHA: "cdk-sha-old"}, // Different from dev
				},
			},
		},
	}

	// Verify config recognizes external deploys
	require.True(t, cicdFile.Config.IsPrimary())
	require.False(t, cicdFile.Config.IsSatellite())

	extDeploy, extRepo := cicdFile.Config.GetExternalDeploy("cdk")
	require.NotNil(t, extDeploy)
	require.NotNil(t, extRepo)
	assert.Equal(t, "cdk", extDeploy.Name)
	assert.Equal(t, "example/cdk", extRepo.Repo)

	allExtDeploys := cicdFile.Config.GetAllExternalDeploys()
	assert.Len(t, allExtDeploys, 1)

	allExtDeployNames := cicdFile.Config.GetAllExternalDeployNames()
	assert.Contains(t, allExtDeployNames, "cdk")

	// Verify external state is tracked
	devState := cicdFile.State["dev"]
	require.NotNil(t, devState.External)
	require.NotNil(t, devState.External["cdk"])
	assert.Equal(t, "cdk-sha-123", devState.External["cdk"].SHA)

	testState := cicdFile.State["test"]
	require.NotNil(t, testState.External)
	require.NotNil(t, testState.External["cdk"])
	assert.Equal(t, "cdk-sha-old", testState.External["cdk"].SHA)
}

// TestMixedLocalAndExternalDeploys tests configuration with both local and
// external deploys working together.
func TestMixedLocalAndExternalDeploys(t *testing.T) {
	// Create temp directory with mock workflow files
	baseDir := t.TempDir()
	createMockWorkflow(t, baseDir, ".github/workflows/deploy-api.yaml")
	createMockWorkflow(t, baseDir, ".github/workflows/deploy-infra.yaml")

	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "api", Workflow: ".github/workflows/deploy-api.yaml"},
			{Name: "infra", Workflow: ".github/workflows/deploy-infra.yaml", Triggers: []string{"terraform/**"}},
		},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
			{
				Repo: "example/k8s-manifests",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "k8s", Workflow: "example/k8s-manifests/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	// Test promote workflow generation
	promoteGen := NewPromoteGenerator(cfg, baseDir)
	promoteContent, err := promoteGen.Generate()
	require.NoError(t, err)

	// Should have all local deploys
	assert.Contains(t, promoteContent, "deploy-api:")
	assert.Contains(t, promoteContent, "deploy-infra:")

	// Should have all external deploys
	assert.Contains(t, promoteContent, "deploy-cdk:")
	assert.Contains(t, promoteContent, "deploy-k8s:")

	// Should have all rollback jobs
	assert.Contains(t, promoteContent, "rollback-api:")
	assert.Contains(t, promoteContent, "rollback-infra:")
	assert.Contains(t, promoteContent, "rollback-cdk:")
	assert.Contains(t, promoteContent, "rollback-k8s:")

	// Test orchestrate workflow generation
	orchestrateGen := NewGenerator(cfg, baseDir)
	orchestrateContent, err := orchestrateGen.Generate()
	require.NoError(t, err)

	// Should include local deploys in execution
	assert.Contains(t, orchestrateContent, "api")
	assert.Contains(t, orchestrateContent, "infra")
}

// TestSatelliteConfigNoExternal tests that satellite repos correctly configure
// notify without needing external deploys.
func TestSatelliteConfigNoExternal(t *testing.T) {
	// Create temp directory with mock workflow file
	baseDir := t.TempDir()
	createMockWorkflow(t, baseDir, ".github/workflows/deploy-cdk.yaml")

	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev", "test", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "cdk", Workflow: ".github/workflows/deploy-cdk.yaml", Triggers: []string{"cdk/**"}},
		},
		Notify: &config.NotifyConfig{
			Repo:     "example/primary-backend",
			Workflow: ".github/workflows/external-update.yaml",
		},
	}

	// Should be satellite, not primary
	assert.False(t, cfg.IsPrimary())
	assert.True(t, cfg.IsSatellite())

	// Should have no external deploys
	assert.Empty(t, cfg.GetAllExternalDeploys())
	assert.Empty(t, cfg.GetAllExternalDeployNames())

	// Generate orchestrate workflow with proper baseDir
	gen := NewGenerator(cfg, baseDir)
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have notify primary step
	assert.Contains(t, content, "Notify Primary")
	assert.Contains(t, content, "example/primary-backend")

	// Should still have local deploys
	assert.Contains(t, content, "cdk")
}

// TestPrimaryWithoutExternal tests that a repo can be primary-like (have deploys)
// but not have external repos configured.
func TestPrimaryWithoutExternal(t *testing.T) {
	// Create temp directory with mock workflow file
	baseDir := t.TempDir()
	createMockWorkflow(t, baseDir, ".github/workflows/deploy.yaml")

	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "app", Workflow: ".github/workflows/deploy.yaml"},
		},
		// No External or Notify configured
	}

	// Should not be primary (no external) or satellite (no notify)
	assert.False(t, cfg.IsPrimary())
	assert.False(t, cfg.IsSatellite())

	// Promote workflow should still work without external deploys
	gen := NewPromoteGenerator(cfg, baseDir)
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have local deploy
	assert.Contains(t, content, "deploy-app:")

	// Should not have external deploy references
	assert.NotContains(t, content, "(external)")
}

// TestExternalWorkflowResolution tests that external workflow paths are correctly
// resolved with refs appended when not specified.
func TestExternalWorkflowResolution(t *testing.T) {
	tests := []struct {
		name         string
		workflow     string
		ref          string
		wantContains string
		description  string
	}{
		{
			name:         "workflow with repo path gets ref appended",
			workflow:     "example/cdk/.github/workflows/deploy.yaml",
			ref:          "main",
			wantContains: "example/cdk/.github/workflows/deploy.yaml@main",
			description:  "External workflow path should have ref appended",
		},
		{
			name:         "workflow already with ref unchanged",
			workflow:     "example/cdk/.github/workflows/deploy.yaml@v1.0.0",
			ref:          "main",
			wantContains: "example/cdk/.github/workflows/deploy.yaml@v1.0.0",
			description:  "Workflow with existing ref should not change",
		},
		{
			name:         "local workflow path uses relative",
			workflow:     ".github/workflows/deploy.yaml",
			ref:          "main",
			wantContains: "./.github/workflows/deploy.yaml",
			description:  "Local workflow should use ./ prefix",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := &config.TrunkConfig{
				TrunkBranch:  "master",
				Environments: []string{"dev", "prod"},
				Deploys: []config.DeployConfig{
					{Name: "app", Workflow: ".github/workflows/deploy.yaml"},
				},
				External: []config.ExternalRepoConfig{
					{
						Repo: "example/cdk",
						Ref:  tt.ref,
						Deploys: []config.ExternalDeployConfig{
							{Name: "cdk", Workflow: tt.workflow},
						},
					},
				},
			}

			gen := NewPromoteGenerator(cfg, "/tmp")
			content, err := gen.Generate()
			require.NoError(t, err)

			assert.Contains(t, content, tt.wantContains, tt.description)
		})
	}
}

// TestRollbackJobConditions tests that rollback job conditions are correctly
// generated for multi-repo scenarios.
func TestRollbackJobConditions(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "app", Workflow: ".github/workflows/deploy-app.yaml"},
		},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewPromoteGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have rollback for local deploy
	assert.Contains(t, content, "rollback-app:")
	assert.Contains(t, content, "name: Rollback app")

	// Should have rollback for external deploy
	assert.Contains(t, content, "rollback-cdk:")
	assert.Contains(t, content, "name: Rollback cdk (external)")

	// Rollback conditions should check:
	// 1. rollback_on_failure enabled
	// 2. rollback_sha not empty
	// 3. This deploy succeeded
	// 4. At least one deploy failed
	lines := strings.Split(content, "\n")
	inRollbackApp := false
	inRollbackCdk := false
	foundAppCondition := false
	foundCdkCondition := false

	for _, line := range lines {
		if strings.Contains(line, "rollback-app:") {
			inRollbackApp = true
			inRollbackCdk = false
		}
		if strings.Contains(line, "rollback-cdk:") {
			inRollbackApp = false
			inRollbackCdk = true
		}
		if inRollbackApp && strings.Contains(line, "needs.deploy-app.result == 'success'") {
			foundAppCondition = true
		}
		if inRollbackCdk && strings.Contains(line, "needs.deploy-cdk.result == 'success'") {
			foundCdkCondition = true
		}
	}

	assert.True(t, foundAppCondition, "Rollback-app should check deploy-app succeeded")
	assert.True(t, foundCdkCondition, "Rollback-cdk should check deploy-cdk succeeded")

	// Failure detection should include all deploys (local and external)
	assert.Contains(t, content, "needs.deploy-app.result == 'failure'")
	assert.Contains(t, content, "needs.deploy-cdk.result == 'failure'")
}

// TestExternalUpdateGenerator_NotPrimary tests that the external-update generator
// correctly fails for non-primary repos.
func TestExternalUpdateGenerator_NotPrimary(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "app", Workflow: ".github/workflows/deploy.yaml"},
		},
		// No External configured - not a primary repo
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	_, err := gen.Generate()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not configured as primary")
}

// TestExternalUpdateGenerator_HasConcurrencyBlock asserts the generated
// external-update workflow declares a top-level concurrency: block scoped per
// component and per ref ("cascade-external-${{ inputs.deploy_name }}-${{ github.ref }}").
// Distinct upstream components land in distinct groups so both run when they
// notify the same downstream repo at the same time; a component still
// serializes against itself. The group must NOT be orchestrate's shared
// ref-scoped key, which would let GitHub cancel all-but-the-latest pending run
// and silently drop a component's state write. cancel-in-progress is false
// because a dropped mid-flight write leaves the manifest inconsistent;
// cross-writer manifest contention is handled by commitWithApplicationRetry.
func TestExternalUpdateGenerator_HasConcurrencyBlock(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "\nconcurrency:\n", "external-update workflow must declare top-level concurrency:")
	group := concurrencyGroupLine(t, content)
	assert.Equal(t, "  group: cascade-external-${{ inputs.deploy_name }}-${{ github.ref }}", group,
		"external-update default concurrency group must be scoped per component so distinct components run concurrently")
	assert.NotContains(t, group, "orchestrate-${{ github.ref }}",
		"external-update group must NOT share orchestrate's shared group: that cancels concurrent component updates")
	assert.Contains(t, group, "inputs.deploy_name", "external-update group must scope by deploy_name so distinct components do not collide")
	assert.NotContains(t, group, "inputs.source_repo", "external-update group must NOT scope by source_repo")
	assert.NotContains(t, group, "inputs.environment", "external-update group must NOT scope by environment")
	assert.Contains(t, content, "cancel-in-progress: false", "external-update default must queue, not cancel")
}

// TestExternalUpdateGenerator_DistinctComponentsGetDistinctGroups asserts that
// two different components (distinct deploy_name) end up in DIFFERENT
// concurrency groups, so artifact-a and artifact-b both run to completion when
// they notify the same downstream repo concurrently. The group key is the same
// expression text for every run; what differs at runtime is the deploy_name
// input GitHub substitutes. We assert the key carries inputs.deploy_name (and
// is not the shared orchestrate group) because that is what makes the runtime
// groups distinct.
func TestExternalUpdateGenerator_DistinctComponentsGetDistinctGroups(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "artifact-a", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
					{Name: "artifact-b", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	group := concurrencyGroupLine(t, content)
	// The generated key parameterizes on inputs.deploy_name, so at runtime
	// artifact-a -> cascade-external-artifact-a-<ref> and
	// artifact-b -> cascade-external-artifact-b-<ref>: distinct groups, both run.
	assert.Equal(t, "  group: cascade-external-${{ inputs.deploy_name }}-${{ github.ref }}", group,
		"the concurrency group must parameterize on inputs.deploy_name so distinct components resolve to distinct groups")
	assert.NotEqual(t, "  group: orchestrate-${{ github.ref }}", group,
		"the shared orchestrate group would put all components in one queue and cancel all but the latest pending run")
}

// TestExternalUpdateGenerator_InputsAreNotInterpolatedIntoRun asserts that the
// generated "Update External State" step never substitutes workflow_dispatch
// inputs directly into the shell script text. GitHub Actions expands ${{ ... }}
// into the run: body before the shell parses it, so a value carrying a single
// quote, backtick, or $(...) would break out of its argument and execute as
// shell. Every untrusted input must instead be bound to a step-level env: var
// and referenced as a quoted shell variable.
func TestExternalUpdateGenerator_InputsAreNotInterpolatedIntoRun(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	runBody := stepRunBody(t, content, "Update External State")

	untrusted := []string{
		"${{ inputs.source_repo }}",
		"${{ inputs.deploy_name }}",
		"${{ inputs.environment }}",
		"${{ inputs.sha }}",
		"${{ inputs.version }}",
		"${{ inputs.artifacts }}",
	}
	for _, expr := range untrusted {
		assert.NotContainsf(t, runBody, expr,
			"untrusted input %q must not be interpolated into the run: body; bind it to env: and reference the shell variable", expr)
	}
	// No ${{ inputs.* }} expansion of any kind should remain in the run body.
	assert.NotContains(t, runBody, "${{ inputs.",
		"no workflow_dispatch input may be interpolated into the run: shell body")

	// The values must instead flow through a step-level env: mapping...
	assert.Contains(t, content, "SOURCE_REPO: ${{ inputs.source_repo }}")
	assert.Contains(t, content, "DEPLOY_NAME: ${{ inputs.deploy_name }}")
	assert.Contains(t, content, "ENVIRONMENT: ${{ inputs.environment }}")
	assert.Contains(t, content, "SHA: ${{ inputs.sha }}")
	assert.Contains(t, content, "VERSION: ${{ inputs.version }}")
	assert.Contains(t, content, "ARTIFACTS: ${{ inputs.artifacts }}")

	// ...and be consumed as quoted shell variables in the verb invocation.
	assert.Contains(t, runBody, "--source-repo \"$SOURCE_REPO\"")
	assert.Contains(t, runBody, "--deploy-name \"$DEPLOY_NAME\"")
	assert.Contains(t, runBody, "--environment \"$ENVIRONMENT\"")
	assert.Contains(t, runBody, "--sha \"$SHA\"")
	assert.Contains(t, runBody, "--version \"$VERSION\"")
	assert.Contains(t, runBody, "--artifacts \"$ARTIFACTS\"")
}

// TestExternalUpdateGenerator_ConcurrencyOverride asserts that a manifest-level
// concurrency config is forwarded to the generated external-update workflow.
func TestExternalUpdateGenerator_ConcurrencyOverride(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
		Concurrency: &config.ConcurrencyConfig{
			Group:            "my-custom-external",
			CancelInProgress: true,
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "group: my-custom-external", "custom group must propagate to external-update")
	assert.Contains(t, content, "cancel-in-progress: true", "custom cancel_in_progress must propagate to external-update")
}

// TestExternalUpdateGenerator_CheckoutUsesStateToken asserts that the receiver
// checkout step uses the configured state token (not the hardcoded GITHUB_TOKEN)
// so that manifest pushes are not blocked by branch protection rules on the
// primary repo. When state_token is unset the checkout falls back to the
// default GITHUB_TOKEN expression for back-compat.
func TestExternalUpdateGenerator_CheckoutUsesStateToken(t *testing.T) {
	externalRepos := []config.ExternalRepoConfig{
		{
			Repo: "example/cdk-infra",
			Ref:  "main",
			Deploys: []config.ExternalDeployConfig{
				{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
			},
		},
	}

	t.Run("state_token configured", func(t *testing.T) {
		cfg := &config.TrunkConfig{
			TrunkBranch:  "main",
			Environments: []string{"dev", "prod"},
			External:     externalRepos,
			StateToken:   "CASCADE_STATE_TOKEN",
		}
		gen := NewExternalUpdateGenerator(cfg, "/tmp")
		content, err := gen.Generate()
		require.NoError(t, err)

		// Extract the checkout step block (everything up to the next "- name:" step)
		// so we assert on the checkout token in isolation, not on tokens used in
		// other steps (e.g., the setup-cli step which uses the release token).
		checkoutSection := checkoutStepBlock(t, content)
		assert.Contains(t, checkoutSection, "token: ${{ secrets.CASCADE_STATE_TOKEN }}",
			"checkout must use the configured state token so the manifest push is not blocked by branch protection")
		assert.NotContains(t, checkoutSection, "token: ${{ secrets.GITHUB_TOKEN }}",
			"when state_token is set, GITHUB_TOKEN must not appear as the checkout token")
		assert.Contains(t, checkoutSection, "fetch-depth: 0",
			"checkout must use fetch-depth: 0 for parity with other state-writers")
	})

	t.Run("state_token unset uses GITHUB_TOKEN back-compat", func(t *testing.T) {
		cfg := &config.TrunkConfig{
			TrunkBranch:  "main",
			Environments: []string{"dev", "prod"},
			External:     externalRepos,
		}
		gen := NewExternalUpdateGenerator(cfg, "/tmp")
		content, err := gen.Generate()
		require.NoError(t, err)

		checkoutSection := checkoutStepBlock(t, content)
		assert.Contains(t, checkoutSection, "token: ${{ secrets.GITHUB_TOKEN }}",
			"when state_token is unset, checkout must fall back to the default GITHUB_TOKEN for back-compat")
		assert.Contains(t, checkoutSection, "fetch-depth: 0",
			"checkout must use fetch-depth: 0 regardless of token configuration")
	})
}

// TestExternalUpdateGenerator_DefaultConcurrencyIsPerComponent asserts that,
// with no explicit concurrency config, the external-update workflow uses a
// per-component, per-ref group ("cascade-external-${{ inputs.deploy_name }}-${{ github.ref }}")
// rather than orchestrate's shared group. The per-component key lets distinct
// upstream components run concurrently against the same downstream repo;
// commitWithApplicationRetry serializes the actual manifest push.
// cancel-in-progress must remain false to never drop a live state write.
func TestExternalUpdateGenerator_DefaultConcurrencyIsPerComponent(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "\nconcurrency:\n", "external-update workflow must declare top-level concurrency:")
	group := concurrencyGroupLine(t, content)
	assert.Equal(t, "  group: cascade-external-${{ inputs.deploy_name }}-${{ github.ref }}", group,
		"external-update default concurrency group must be per-component so distinct components do not cancel each other")
	assert.NotEqual(t, "  group: orchestrate-${{ github.ref }}", group,
		"external-update must NOT reuse orchestrate's shared group: that is the cancellation regression")
	assert.Contains(t, content, "cancel-in-progress: false",
		"external-update must never cancel a live state write; cancel-in-progress must be false")
}

// TestNotifyPrimaryStep_BuildOnlySatellite_EmitsDeployName verifies that a
// build-only satellite (builds + notify, zero deploys) still emits a non-empty
// deploy_name in the dispatch to the primary's external-update workflow. The
// consumer declares deploy_name as required: true, so omitting it produces a
// live 422 "Required input 'deploy_name' not provided". The fallback is the
// first build name, which represents this satellite's artifact.
func TestNotifyPrimaryStep_BuildOnlySatellite_EmitsDeployName(t *testing.T) {
	baseDir := t.TempDir()
	createMockWorkflow(t, baseDir, ".github/workflows/build-shared.yaml")

	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev"},
		Builds: []config.BuildConfig{
			{Name: "shared", Workflow: ".github/workflows/build-shared.yaml", Triggers: []string{"src/**"}},
		},
		// No deploys: this is a build-only artifact satellite.
		Notify: &config.NotifyConfig{
			Repo:     "example/primary-backend",
			Workflow: ".github/workflows/external-update.yaml",
		},
	}

	require.True(t, cfg.IsSatellite())
	require.Empty(t, cfg.Deploys)

	gen := NewGenerator(cfg, baseDir)
	content, err := gen.Generate()
	require.NoError(t, err)

	require.Contains(t, content, "Notify Primary Repo")
	// The dispatch inputs MUST include a non-empty deploy_name. Falls back to
	// the first build name when there are no deploys.
	assert.Contains(t, content, "deploy_name: 'shared',",
		"build-only satellite must emit a non-empty deploy_name (consumer requires it)")
}

// TestNotifyPrimaryStep_NoStrayDotInJobsAccessor verifies the github-script
// context accessor uses context.jobs['id'] form with no stray dot before the
// bracket. The earlier context.jobs.['id'] form is invalid JavaScript and would
// fail at runtime for any satellite that collects deploy outputs.
func TestNotifyPrimaryStep_NoStrayDotInJobsAccessor(t *testing.T) {
	baseDir := t.TempDir()
	createMockWorkflow(t, baseDir, ".github/workflows/deploy-cdk.yaml")

	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev"},
		Deploys: []config.DeployConfig{
			{Name: "cdk", Workflow: ".github/workflows/deploy-cdk.yaml", Triggers: []string{"cdk/**"}},
		},
		Notify: &config.NotifyConfig{
			Repo:     "example/primary-backend",
			Workflow: ".github/workflows/external-update.yaml",
		},
	}

	gen := NewGenerator(cfg, baseDir)
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.NotContains(t, content, "context.jobs.[",
		"github-script accessor must not have a stray dot before the bracket")
}

// onUpdatePrimaryConfig returns a primary config with one external deploy that
// opts in to on_update.deploy and one that does not, so tests can assert the
// scoped deploy job is emitted only for the opted-in component.
func onUpdatePrimaryConfig() *config.TrunkConfig {
	return &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev", "test", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{
						Name:     "cdk",
						Workflow: "example/cdk-infra/.github/workflows/deploy.yaml",
						OnUpdate: &config.OnUpdateConfig{
							Deploy: &config.OnUpdateDeploy{
								Workflow: "example/cdk-infra/.github/workflows/deploy.yaml",
							},
						},
					},
				},
			},
			{
				Repo: "example/k8s-manifests",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					// No on_update: this component stays record-only and must not
					// produce a deploy job.
					{Name: "k8s", Workflow: "example/k8s-manifests/.github/workflows/deploy.yaml"},
				},
			},
		},
	}
}

// TestExternalUpdateGenerator_OnUpdateDeploy_ScopedJob verifies that an external
// deploy declaring on_update.deploy produces a scoped deploy_<name> job that is
// gated on the update job succeeding and on the dispatched component, and that
// the secrets-inherit and with: inputs are wired.
func TestExternalUpdateGenerator_OnUpdateDeploy_ScopedJob(t *testing.T) {
	gen := NewExternalUpdateGenerator(onUpdatePrimaryConfig(), "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	// The opted-in component gets a deterministically named scoped deploy job.
	assert.Contains(t, content, "  deploy_cdk:")
	assert.Contains(t, content, "    needs: update\n")
	// Gated on the update job succeeding AND the dispatched component matching.
	assert.Contains(t, content,
		"if: ${{ needs.update.result == 'success' && inputs.deploy_name == 'cdk' }}")
	// Cross-repo workflow path keeps its ref.
	assert.Contains(t, content,
		"uses: example/cdk-infra/.github/workflows/deploy.yaml@main")
	// Scoped with: inputs forward the dispatched run's environment/sha/version.
	assert.Contains(t, content, "environment: ${{ inputs.environment }}")
	assert.Contains(t, content, "sha: ${{ inputs.sha }}")
	assert.Contains(t, content, "deploy_name: ${{ inputs.deploy_name }}")
	assert.Contains(t, content, "secrets: inherit")

	// The component without on_update must not get a deploy job.
	assert.NotContains(t, content, "deploy_k8s:")
}

// TestExternalUpdateGenerator_NoOnUpdate_RecordOnlyByteIdentical proves the
// back-compat guarantee: when no external deploy declares on_update, the
// generated receiver is byte-identical to the record-only output and contains no
// deploy job at all.
func TestExternalUpdateGenerator_NoOnUpdate_RecordOnlyByteIdentical(t *testing.T) {
	// A config identical to the on_update case but with the on_update blocks
	// stripped. The generated bytes must match a hand-built record-only baseline.
	recordOnly := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev", "test", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
			{
				Repo: "example/k8s-manifests",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "k8s", Workflow: "example/k8s-manifests/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewExternalUpdateGenerator(recordOnly, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	// No deploy job is emitted when no component opts in.
	assert.NotContains(t, content, "deploy_cdk:")
	assert.NotContains(t, content, "deploy_k8s:")
	assert.NotContains(t, content, "needs: update")

	// The only job is the update job (exactly one job key under jobs:).
	assert.Equal(t, 1, strings.Count(content, "  update:\n"),
		"record-only receiver must contain exactly the update job")
}

// TestExternalUpdateGenerator_OnUpdateDeploy_Deterministic asserts the generated
// receiver is byte-stable across repeated generations when on_update.deploy is
// configured, matching the package determinism guarantee.
func TestExternalUpdateGenerator_OnUpdateDeploy_Deterministic(t *testing.T) {
	cfg := onUpdatePrimaryConfig()
	first, err := NewExternalUpdateGenerator(cfg, "/tmp").Generate()
	require.NoError(t, err)
	for i := 0; i < 20; i++ {
		next, err := NewExternalUpdateGenerator(cfg, "/tmp").Generate()
		require.NoError(t, err)
		require.Equal(t, first, next, "external-update generation must be deterministic")
	}
}

// TestExternalUpdateGenerator_OnUpdateDeploy_LocalWorkflowPath verifies a local
// on_update.deploy.workflow is normalized to the canonical ./ uses: form.
func TestExternalUpdateGenerator_OnUpdateDeploy_LocalWorkflowPath(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{
						Name:     "cdk",
						Workflow: "example/cdk-infra/.github/workflows/deploy.yaml",
						OnUpdate: &config.OnUpdateConfig{
							Deploy: &config.OnUpdateDeploy{
								Workflow: ".github/workflows/deploy-cdk.yaml",
							},
						},
					},
				},
			},
		},
	}

	content, err := NewExternalUpdateGenerator(cfg, "/tmp").Generate()
	require.NoError(t, err)
	assert.Contains(t, content, "uses: ./.github/workflows/deploy-cdk.yaml")
}
