package generate

import (
	"fmt"
	"strings"

	"github.com/stablekernel/cascade/internal/config"
)

// ExternalUpdateGenerator handles external-update workflow generation
type ExternalUpdateGenerator struct {
	config  *config.TrunkConfig
	baseDir string
}

// NewExternalUpdateGenerator creates a new external-update workflow generator
func NewExternalUpdateGenerator(cfg *config.TrunkConfig, baseDir string) *ExternalUpdateGenerator {
	return &ExternalUpdateGenerator{
		config:  cfg,
		baseDir: baseDir,
	}
}

// getCLIRef returns the Git ref for the cascade self-action. The default
// (cli_version unset or "latest") resolves to config.DefaultCLIVersion, an
// immutable release tag, so consumers never run an unpinned mutable ref.
// "beta" is the explicit opt-in escape hatch to the "master" branch.
func (g *ExternalUpdateGenerator) getCLIRef() string {
	if g.config.CLIVersion == "beta" {
		return "master" // Explicit opt-in escape hatch to trunk.
	}
	return g.config.GetCLIVersion()
}

// getReleaseTokenRef returns the token expression for release operations.
func (g *ExternalUpdateGenerator) getReleaseTokenRef() string {
	return g.config.GetReleaseToken()
}

// getStateTokenRef returns the token expression used to write manifest state to
// the trunk branch. Users configure the full expression via the state_token
// config option; it defaults to "${{ secrets.GITHUB_TOKEN }}".
func (g *ExternalUpdateGenerator) getStateTokenRef() string {
	return g.config.GetStateToken()
}

// getManifestFilePath returns the manifest file path for use in generated scripts.
func (g *ExternalUpdateGenerator) getManifestFilePath() string {
	return g.config.GetManifestFile()
}

// getManifestKey returns the manifest key for nested access
func (g *ExternalUpdateGenerator) getManifestKey() string {
	return g.config.GetManifestKey()
}

// Generate creates the external-update workflow content
func (g *ExternalUpdateGenerator) Generate() (string, error) {
	if !g.config.IsPrimary() {
		return "", fmt.Errorf("cannot generate external-update workflow: repo is not configured as primary (no external repos)")
	}

	var sb strings.Builder

	g.writeHeader(&sb)
	g.writeWorkflowTrigger(&sb)
	g.writePermissions(&sb)
	g.writeConcurrency(&sb)
	g.writeJob(&sb)

	return sb.String(), nil
}

func (g *ExternalUpdateGenerator) writeHeader(sb *strings.Builder) {
	sb.WriteString("# AUTO-GENERATED by cascade - DO NOT EDIT MANUALLY\n")
	fmt.Fprintf(sb, "# Regenerate with: cascade generate-workflow --config %s\n\n", g.config.GetManifestFile())
}

func (g *ExternalUpdateGenerator) writeWorkflowTrigger(sb *strings.Builder) {
	sb.WriteString("name: External Update\n\n")
	sb.WriteString("on:\n")
	sb.WriteString("  workflow_dispatch:\n")
	sb.WriteString("    inputs:\n")
	sb.WriteString("      source_repo:\n")
	sb.WriteString("        description: 'Source repository (e.g., org/cdk-infra)'\n")
	sb.WriteString("        type: string\n")
	sb.WriteString("        required: true\n")
	sb.WriteString("      deploy_name:\n")
	sb.WriteString("        description: 'Deploy name (e.g., cdk)'\n")
	sb.WriteString("        type: string\n")
	sb.WriteString("        required: true\n")
	sb.WriteString("      environment:\n")
	sb.WriteString("        description: 'Target environment'\n")
	sb.WriteString("        type: string\n")
	sb.WriteString("        required: true\n")
	sb.WriteString("      sha:\n")
	sb.WriteString("        description: 'Commit SHA from source repo'\n")
	sb.WriteString("        type: string\n")
	sb.WriteString("        required: true\n")
	sb.WriteString("      version:\n")
	sb.WriteString("        description: 'Version from source repo (optional)'\n")
	sb.WriteString("        type: string\n")
	sb.WriteString("        required: false\n")
	sb.WriteString("      artifacts:\n")
	sb.WriteString("        description: 'Artifacts JSON (optional)'\n")
	sb.WriteString("        type: string\n")
	sb.WriteString("        required: false\n\n")
}

func (g *ExternalUpdateGenerator) writePermissions(sb *strings.Builder) {
	sb.WriteString("permissions:\n")
	sb.WriteString("  contents: write\n\n")
}

func (g *ExternalUpdateGenerator) writeJob(sb *strings.Builder) {
	sb.WriteString("jobs:\n")
	sb.WriteString("  update:\n")
	sb.WriteString("    name: Update External State\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    steps:\n")
	// The receiver checks out with the state token (the push identity) so that
	// the manifest push is not blocked by branch protection rules on the primary
	// repo. fetch-depth: 0 is required for parity with orchestrate/promote/hotfix
	// state-writers, which also need the full history. When state_token is unset
	// this falls back to GITHUB_TOKEN for back-compat.
	writeActionStep(sb, g.config, "      ", actionCheckout)
	sb.WriteString("        with:\n")
	sb.WriteString("          fetch-depth: 0\n")
	fmt.Fprintf(sb, "          token: %s\n", g.getStateTokenRef())
	sb.WriteString("\n")

	// Setup CLI
	sb.WriteString("      - name: Setup CLI\n")
	fmt.Fprintf(sb, "        uses: stablekernel/cascade/.github/actions/setup-cli@%s\n", g.getCLIRef())
	sb.WriteString("        with:\n")
	fmt.Fprintf(sb, "          token: %s\n", g.getReleaseTokenRef())
	fmt.Fprintf(sb, "          version: %s\n", g.config.GetCLIVersion())
	sb.WriteString("\n")

	// Configure git identity so the verb's commit/push of the manifest state
	// works on a clean runner. `cascade external update` commits and pushes the
	// updated ci.state.<env>.external.<name> via git; without an identity the
	// underlying `git commit` aborts. This mirrors the git-config step the
	// orchestrate/promote/hotfix workflows emit before their state writes, and
	// honors the same git mode + GPG settings.
	sb.WriteString("      - name: Configure Git\n")
	sb.WriteString("        run: |\n")
	writeGitConfigSteps(sb, g.config, "          ")
	sb.WriteString("\n")

	// Run external update.
	//
	// Every workflow_dispatch input is untrusted: GitHub expands ${{ ... }} into
	// the run: script text before the shell parses it, so a value carrying a single
	// quote, backtick, or $(...) would break out of its argument and execute as
	// shell. Bind each input to a step-level env: variable and reference it as a
	// quoted shell variable so the value reaches the verb as a single inert
	// argument regardless of its contents.
	sb.WriteString("      - name: Update External State\n")
	sb.WriteString("        env:\n")
	sb.WriteString("          SOURCE_REPO: ${{ inputs.source_repo }}\n")
	sb.WriteString("          DEPLOY_NAME: ${{ inputs.deploy_name }}\n")
	sb.WriteString("          ENVIRONMENT: ${{ inputs.environment }}\n")
	sb.WriteString("          SHA: ${{ inputs.sha }}\n")
	sb.WriteString("          VERSION: ${{ inputs.version }}\n")
	sb.WriteString("          ARTIFACTS: ${{ inputs.artifacts }}\n")
	sb.WriteString("        run: |\n")
	sb.WriteString("          cascade external update \\\n")
	fmt.Fprintf(sb, "            --config %s \\\n", g.getManifestFilePath())
	fmt.Fprintf(sb, "            --manifest-key %s \\\n", g.getManifestKey())
	sb.WriteString("            --source-repo \"$SOURCE_REPO\" \\\n")
	sb.WriteString("            --deploy-name \"$DEPLOY_NAME\" \\\n")
	sb.WriteString("            --environment \"$ENVIRONMENT\" \\\n")
	sb.WriteString("            --sha \"$SHA\" \\\n")
	sb.WriteString("            --version \"$VERSION\" \\\n")
	sb.WriteString("            --artifacts \"$ARTIFACTS\"\n")
}

// writeConcurrency emits a top-level concurrency: block on the external-update
// workflow. The default group is scoped PER COMPONENT and per ref
// ("cascade-external-${{ inputs.deploy_name }}-${{ github.ref }}"). Each
// upstream component (distinct deploy_name) lands in its own queue, so two
// components notifying the same downstream repo at the same time both run to
// completion instead of one cancelling the other. A given component still
// serializes against itself: GitHub keeps only the latest pending run per
// group, so a burst from one component collapses to the newest, which is the
// intended last-writer-wins for that single slot.
//
// Cross-component contention on the shared manifest file, and contention with
// the orchestrate state-writer, is resolved by commitWithApplicationRetry in
// the external update verb (fetch / reset / re-apply on a non-fast-forward
// push), not by a shared concurrency group. A single shared group would
// serialize distinct components and let GitHub's "keep only the latest pending
// run" rule drop all but one component's write, which is the regression this
// per-component key fixes.
//
// inputs.deploy_name is a workflow-level expression here, not shell text, so it
// is inert in the concurrency key and carries none of the run-body injection
// risk that the env-bound inputs guard against.
//
// cancel-in-progress is always false by default: dropping a mid-flight write
// leaves the manifest inconsistent. When the manifest explicitly sets
// concurrency.group, that value is forwarded as-is (via GetConcurrencyGroup)
// so operators can override the group, and cancel-in-progress follows the
// explicit config value.
func (g *ExternalUpdateGenerator) writeConcurrency(sb *strings.Builder) {
	sb.WriteString("concurrency:\n")
	if g.config.Concurrency != nil && g.config.Concurrency.Group != "" {
		// Operator override: forward the explicit group verbatim.
		fmt.Fprintf(sb, "  group: %s\n", g.config.Concurrency.Group)
	} else {
		// Default: per-component, per-ref group so distinct upstream components
		// run concurrently against the same downstream repo.
		sb.WriteString("  group: cascade-external-${{ inputs.deploy_name }}-${{ github.ref }}\n")
	}
	if g.config.Concurrency != nil {
		fmt.Fprintf(sb, "  cancel-in-progress: %t\n", g.config.Concurrency.CancelInProgress)
	} else {
		sb.WriteString("  cancel-in-progress: false\n")
	}
	sb.WriteString("\n")
}
