package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stablekernel/cascade/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// mockWorkflowContent returns a minimal workflow YAML that the generator can parse
const mockWorkflowContent = `name: Mock Deploy
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    outputs:
      deployed_sha:
        value: ${{ jobs.deploy.outputs.sha }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ github.sha }}
    steps:
      - run: echo "deploying"
`

// createMockWorkflow creates a mock workflow file in a temp directory
func createMockWorkflow(t *testing.T, baseDir, workflowPath string) {
	t.Helper()
	fullPath := filepath.Join(baseDir, workflowPath)
	err := os.MkdirAll(filepath.Dir(fullPath), 0755)
	require.NoError(t, err)
	err = os.WriteFile(fullPath, []byte(mockWorkflowContent), 0644)
	require.NoError(t, err)
}

// =============================================================================
// Multi-Repo Orchestration Integration Tests
// =============================================================================

// TestExternalUpdateWorkflow_Generation tests that the external-update workflow
// is correctly generated for primary repos that coordinate satellite deploys.
func TestExternalUpdateWorkflow_Generation(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
			{
				Repo: "example/k8s-manifests",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "k8s", Workflow: "example/k8s-manifests/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have workflow header
	assert.Contains(t, content, "# AUTO-GENERATED by cascade")
	assert.Contains(t, content, "name: External Update")

	// Should have workflow_dispatch trigger with inputs for external updates
	assert.Contains(t, content, "workflow_dispatch:")
	assert.Contains(t, content, "inputs:")

	// Should accept deploy info as inputs
	assert.Contains(t, content, "source_repo")
	assert.Contains(t, content, "deploy_name")
	assert.Contains(t, content, "environment")
	assert.Contains(t, content, "sha")

	// Should call the external update CLI command
	assert.Contains(t, content, "cascade external update")
	assert.Contains(t, content, "--source-repo")
	assert.Contains(t, content, "--deploy-name")
	assert.Contains(t, content, "--environment")
	assert.Contains(t, content, "--sha")

	// Should configure a git identity before the verb runs. `cascade external
	// update` commits and pushes the manifest state via git, which aborts on a
	// clean runner with no identity, so the workflow must set one first.
	assert.Contains(t, content, "Configure Git")
	assert.Contains(t, content, "git config user.name")
	assert.Contains(t, content, "git config user.email")
	assert.Less(t, strings.Index(content, "Configure Git"),
		strings.Index(content, "cascade external update"),
		"git identity must be configured before the update verb commits")
}

// TestSatelliteNotifyPrimary_Generation tests that satellite repos generate
// a notify-primary step in the orchestrate finalize job.
func TestSatelliteNotifyPrimary_Generation(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev", "test", "prod"},
		Notify: &config.NotifyConfig{
			Repo:     "example/primary-backend",
			Workflow: ".github/workflows/external-update.yaml",
		},
	}

	gen := NewGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have notify primary step
	assert.Contains(t, content, "Notify Primary")

	// Should dispatch to the primary repo using workflow dispatch
	assert.Contains(t, content, "example/primary-backend")
	assert.Contains(t, content, "createWorkflowDispatch")

	// Should pass deploy info in payload
	assert.Contains(t, content, "source_repo")
	assert.Contains(t, content, "environment")
	assert.Contains(t, content, "sha")
}

// TestPromoteExternalDeploys_Generation tests that promote workflow correctly
// generates external deploy jobs when external deploys are configured.
func TestPromoteExternalDeploys_Generation(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "app", Workflow: ".github/workflows/deploy-app.yaml"},
		},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewPromoteGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have local deploy job
	assert.Contains(t, content, "deploy-app:")
	assert.Contains(t, content, "name: Deploy app")

	// Should have external deploy job
	assert.Contains(t, content, "deploy-cdk:")
	assert.Contains(t, content, "name: Deploy cdk (external)")

	// Should have prod deploy jobs for cascade mode
	assert.Contains(t, content, "deploy-app-prod:")
	assert.Contains(t, content, "deploy-cdk-prod:")

	// External deploy should use cross-repo workflow_call
	assert.Contains(t, content, "example/cdk-infra/.github/workflows/deploy.yaml@main")

	// Should have external_deploys_to_run output
	assert.Contains(t, content, "external_deploys_to_run:")
	assert.Contains(t, content, "steps.preflight.outputs.external_deploys_to_run")

	// Should have rollback jobs for both local and external
	assert.Contains(t, content, "rollback-app:")
	assert.Contains(t, content, "rollback-cdk:")

	// Finalize needs should include external deploy jobs
	assert.Contains(t, content, "deploy-cdk")
	assert.Contains(t, content, "deploy-cdk-prod")
}

// TestExternalDeployStateTracking tests that preflight correctly identifies
// external deploys that need to run based on state differences.
func TestExternalDeployStateTracking(t *testing.T) {
	// This test covers the integration between config and preflight
	cicdFile := &config.CICDFile{
		Config: &config.TrunkConfig{
			Environments: []string{"dev", "test", "prod"},
			Deploys: []config.DeployConfig{
				{Name: "app"},
			},
			External: []config.ExternalRepoConfig{
				{
					Repo: "example/cdk",
					Ref:  "main",
					Deploys: []config.ExternalDeployConfig{
						{Name: "cdk", Workflow: "example/cdk/.github/workflows/deploy.yaml"},
					},
				},
			},
		},
		State: map[string]*config.EnvState{
			"dev": {
				SHA:     "abc123",
				Version: "v1.0.0-rc.0",
				External: map[string]*config.ExternalDeployState{
					"cdk": {SHA: "cdk-sha-123"},
				},
			},
			"test": {
				SHA:     "def456", // Different from dev
				Version: "v0.9.0",
				External: map[string]*config.ExternalDeployState{
					"cdk": {SHA: "cdk-sha-old"}, // Different from dev
				},
			},
		},
	}

	// Verify config recognizes external deploys
	require.True(t, cicdFile.Config.IsPrimary())
	require.False(t, cicdFile.Config.IsSatellite())

	extDeploy, extRepo := cicdFile.Config.GetExternalDeploy("cdk")
	require.NotNil(t, extDeploy)
	require.NotNil(t, extRepo)
	assert.Equal(t, "cdk", extDeploy.Name)
	assert.Equal(t, "example/cdk", extRepo.Repo)

	allExtDeploys := cicdFile.Config.GetAllExternalDeploys()
	assert.Len(t, allExtDeploys, 1)

	allExtDeployNames := cicdFile.Config.GetAllExternalDeployNames()
	assert.Contains(t, allExtDeployNames, "cdk")

	// Verify external state is tracked
	devState := cicdFile.State["dev"]
	require.NotNil(t, devState.External)
	require.NotNil(t, devState.External["cdk"])
	assert.Equal(t, "cdk-sha-123", devState.External["cdk"].SHA)

	testState := cicdFile.State["test"]
	require.NotNil(t, testState.External)
	require.NotNil(t, testState.External["cdk"])
	assert.Equal(t, "cdk-sha-old", testState.External["cdk"].SHA)
}

// TestMixedLocalAndExternalDeploys tests configuration with both local and
// external deploys working together.
func TestMixedLocalAndExternalDeploys(t *testing.T) {
	// Create temp directory with mock workflow files
	baseDir := t.TempDir()
	createMockWorkflow(t, baseDir, ".github/workflows/deploy-api.yaml")
	createMockWorkflow(t, baseDir, ".github/workflows/deploy-infra.yaml")

	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "api", Workflow: ".github/workflows/deploy-api.yaml"},
			{Name: "infra", Workflow: ".github/workflows/deploy-infra.yaml", Triggers: []string{"terraform/**"}},
		},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
			{
				Repo: "example/k8s-manifests",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "k8s", Workflow: "example/k8s-manifests/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	// Test promote workflow generation
	promoteGen := NewPromoteGenerator(cfg, baseDir)
	promoteContent, err := promoteGen.Generate()
	require.NoError(t, err)

	// Should have all local deploys
	assert.Contains(t, promoteContent, "deploy-api:")
	assert.Contains(t, promoteContent, "deploy-infra:")

	// Should have all external deploys
	assert.Contains(t, promoteContent, "deploy-cdk:")
	assert.Contains(t, promoteContent, "deploy-k8s:")

	// Should have all rollback jobs
	assert.Contains(t, promoteContent, "rollback-api:")
	assert.Contains(t, promoteContent, "rollback-infra:")
	assert.Contains(t, promoteContent, "rollback-cdk:")
	assert.Contains(t, promoteContent, "rollback-k8s:")

	// Test orchestrate workflow generation
	orchestrateGen := NewGenerator(cfg, baseDir)
	orchestrateContent, err := orchestrateGen.Generate()
	require.NoError(t, err)

	// Should include local deploys in execution
	assert.Contains(t, orchestrateContent, "api")
	assert.Contains(t, orchestrateContent, "infra")
}

// TestSatelliteConfigNoExternal tests that satellite repos correctly configure
// notify without needing external deploys.
func TestSatelliteConfigNoExternal(t *testing.T) {
	// Create temp directory with mock workflow file
	baseDir := t.TempDir()
	createMockWorkflow(t, baseDir, ".github/workflows/deploy-cdk.yaml")

	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev", "test", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "cdk", Workflow: ".github/workflows/deploy-cdk.yaml", Triggers: []string{"cdk/**"}},
		},
		Notify: &config.NotifyConfig{
			Repo:     "example/primary-backend",
			Workflow: ".github/workflows/external-update.yaml",
		},
	}

	// Should be satellite, not primary
	assert.False(t, cfg.IsPrimary())
	assert.True(t, cfg.IsSatellite())

	// Should have no external deploys
	assert.Empty(t, cfg.GetAllExternalDeploys())
	assert.Empty(t, cfg.GetAllExternalDeployNames())

	// Generate orchestrate workflow with proper baseDir
	gen := NewGenerator(cfg, baseDir)
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have notify primary step
	assert.Contains(t, content, "Notify Primary")
	assert.Contains(t, content, "example/primary-backend")

	// Should still have local deploys
	assert.Contains(t, content, "cdk")
}

// TestPrimaryWithoutExternal tests that a repo can be primary-like (have deploys)
// but not have external repos configured.
func TestPrimaryWithoutExternal(t *testing.T) {
	// Create temp directory with mock workflow file
	baseDir := t.TempDir()
	createMockWorkflow(t, baseDir, ".github/workflows/deploy.yaml")

	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "app", Workflow: ".github/workflows/deploy.yaml"},
		},
		// No External or Notify configured
	}

	// Should not be primary (no external) or satellite (no notify)
	assert.False(t, cfg.IsPrimary())
	assert.False(t, cfg.IsSatellite())

	// Promote workflow should still work without external deploys
	gen := NewPromoteGenerator(cfg, baseDir)
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have local deploy
	assert.Contains(t, content, "deploy-app:")

	// Should not have external deploy references
	assert.NotContains(t, content, "(external)")
}

// TestExternalWorkflowResolution tests that external workflow paths are correctly
// resolved with refs appended when not specified.
func TestExternalWorkflowResolution(t *testing.T) {
	tests := []struct {
		name         string
		workflow     string
		ref          string
		wantContains string
		description  string
	}{
		{
			name:         "workflow with repo path gets ref appended",
			workflow:     "example/cdk/.github/workflows/deploy.yaml",
			ref:          "main",
			wantContains: "example/cdk/.github/workflows/deploy.yaml@main",
			description:  "External workflow path should have ref appended",
		},
		{
			name:         "workflow already with ref unchanged",
			workflow:     "example/cdk/.github/workflows/deploy.yaml@v1.0.0",
			ref:          "main",
			wantContains: "example/cdk/.github/workflows/deploy.yaml@v1.0.0",
			description:  "Workflow with existing ref should not change",
		},
		{
			name:         "local workflow path uses relative",
			workflow:     ".github/workflows/deploy.yaml",
			ref:          "main",
			wantContains: "./.github/workflows/deploy.yaml",
			description:  "Local workflow should use ./ prefix",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := &config.TrunkConfig{
				TrunkBranch:  "master",
				Environments: []string{"dev", "prod"},
				Deploys: []config.DeployConfig{
					{Name: "app", Workflow: ".github/workflows/deploy.yaml"},
				},
				External: []config.ExternalRepoConfig{
					{
						Repo: "example/cdk",
						Ref:  tt.ref,
						Deploys: []config.ExternalDeployConfig{
							{Name: "cdk", Workflow: tt.workflow},
						},
					},
				},
			}

			gen := NewPromoteGenerator(cfg, "/tmp")
			content, err := gen.Generate()
			require.NoError(t, err)

			assert.Contains(t, content, tt.wantContains, tt.description)
		})
	}
}

// TestRollbackJobConditions tests that rollback job conditions are correctly
// generated for multi-repo scenarios.
func TestRollbackJobConditions(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "app", Workflow: ".github/workflows/deploy-app.yaml"},
		},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewPromoteGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Should have rollback for local deploy
	assert.Contains(t, content, "rollback-app:")
	assert.Contains(t, content, "name: Rollback app")

	// Should have rollback for external deploy
	assert.Contains(t, content, "rollback-cdk:")
	assert.Contains(t, content, "name: Rollback cdk (external)")

	// Rollback conditions should check:
	// 1. rollback_on_failure enabled
	// 2. rollback_sha not empty
	// 3. This deploy succeeded
	// 4. At least one deploy failed
	lines := strings.Split(content, "\n")
	inRollbackApp := false
	inRollbackCdk := false
	foundAppCondition := false
	foundCdkCondition := false

	for _, line := range lines {
		if strings.Contains(line, "rollback-app:") {
			inRollbackApp = true
			inRollbackCdk = false
		}
		if strings.Contains(line, "rollback-cdk:") {
			inRollbackApp = false
			inRollbackCdk = true
		}
		if inRollbackApp && strings.Contains(line, "needs.deploy-app.result == 'success'") {
			foundAppCondition = true
		}
		if inRollbackCdk && strings.Contains(line, "needs.deploy-cdk.result == 'success'") {
			foundCdkCondition = true
		}
	}

	assert.True(t, foundAppCondition, "Rollback-app should check deploy-app succeeded")
	assert.True(t, foundCdkCondition, "Rollback-cdk should check deploy-cdk succeeded")

	// Failure detection should include all deploys (local and external)
	assert.Contains(t, content, "needs.deploy-app.result == 'failure'")
	assert.Contains(t, content, "needs.deploy-cdk.result == 'failure'")
}

// TestExternalUpdateGenerator_NotPrimary tests that the external-update generator
// correctly fails for non-primary repos.
func TestExternalUpdateGenerator_NotPrimary(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "prod"},
		Deploys: []config.DeployConfig{
			{Name: "app", Workflow: ".github/workflows/deploy.yaml"},
		},
		// No External configured - not a primary repo
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	_, err := gen.Generate()
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not configured as primary")
}

// TestExternalUpdateGenerator_HasConcurrencyBlock asserts the generated
// external-update workflow declares a top-level concurrency: block keyed by the bare
// workflow name. Every external update writes back the single shared manifest file
// (cascade external update writes --config then git-pushes that same path)
// regardless of source_repo or environment, so ALL external-update runs race on that
// one non-fast-forward push (#31); the group must serialize every run. cancel-in
// -progress is false because a dropped mid-flight write leaves the manifest in an
// inconsistent state.
func TestExternalUpdateGenerator_HasConcurrencyBlock(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "test", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "\nconcurrency:\n", "external-update workflow must declare top-level concurrency:")
	group := concurrencyGroupLine(t, content)
	assert.Equal(t, "  group: \"${{ github.workflow }}\"", group, "external-update concurrency group must be the bare workflow name to serialize all runs")
	assert.NotContains(t, group, "inputs.source_repo", "external-update group must NOT scope by source_repo: all runs push the same manifest")
	assert.NotContains(t, group, "inputs.environment", "external-update group must NOT scope by environment: all runs push the same manifest")
	assert.Contains(t, content, "cancel-in-progress: false", "external-update default must queue, not cancel")
}

// TestExternalUpdateGenerator_ConcurrencyOverride asserts that a manifest-level
// concurrency config is forwarded to the generated external-update workflow.
func TestExternalUpdateGenerator_ConcurrencyOverride(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "master",
		Environments: []string{"dev", "prod"},
		External: []config.ExternalRepoConfig{
			{
				Repo: "example/cdk-infra",
				Ref:  "main",
				Deploys: []config.ExternalDeployConfig{
					{Name: "cdk", Workflow: "example/cdk-infra/.github/workflows/deploy.yaml"},
				},
			},
		},
		Concurrency: &config.ConcurrencyConfig{
			Group:            "my-custom-external",
			CancelInProgress: true,
		},
	}

	gen := NewExternalUpdateGenerator(cfg, "/tmp")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "group: my-custom-external", "custom group must propagate to external-update")
	assert.Contains(t, content, "cancel-in-progress: true", "custom cancel_in_progress must propagate to external-update")
}
