package generate

// GeneratedFileMarker is the first line written at the top of every file the
// generators emit (workflows and the composite action). It marks a file as
// cascade-owned so tooling can distinguish generated output from hand-written
// files in the same directory. The verify command keys orphan detection off
// this exact string: a file carrying it that the manifest no longer plans is an
// orphan, while a file without it is treated as hand-written and never touched.
//
// The string is load-bearing. Changing it is a breaking change for any repo
// whose committed workflows still carry the old marker, so treat it as stable.
const GeneratedFileMarker = "# AUTO-GENERATED by cascade - DO NOT EDIT MANUALLY"
