package generate

// GeneratedFileMarker is the first line written at the top of every file the
// generators emit (workflows and the composite action). It marks a file as
// cascade-owned so tooling can distinguish generated output from hand-written
// files in the same directory. The verify command keys orphan detection off
// this exact string: a file carrying it that the manifest no longer plans is an
// orphan, while a file without it is treated as hand-written and never touched.
//
// The string is load-bearing. Changing it is a breaking change for any repo
// whose committed workflows still carry the old marker, so treat it as stable.
const GeneratedFileMarker = "# AUTO-GENERATED by cascade - DO NOT EDIT MANUALLY"

// OwnRepoGeneratedFileMarker is the distinct provenance header cascade's own
// self-heal companion carries instead of GeneratedFileMarker. That companion is
// generated (and drift-locked) but lives outside cascade's own manifest
// workflow plan, so it must not be mistaken for a manifest orphan. The verify
// command keys off this exact string to skip such files from the orphan scan
// while still flagging any file that carries the plain GeneratedFileMarker but
// is no longer planned. The two markers deliberately share no substring so a
// GeneratedFileMarker scan never matches an own-repo file, and vice versa.
const OwnRepoGeneratedFileMarker = "# Generated by cascade reconcile --own-repo - DO NOT EDIT MANUALLY"
