package generate

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stablekernel/cascade/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestMergeQueueGenerator_Enabled(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch: "main",
		MergeQueue:  &config.MergeQueueConfig{Enabled: true},
	}
	gen := NewMergeQueueGenerator(cfg, "")
	assert.True(t, gen.Enabled(), "merge_queue.enabled should report enabled")

	// Absent block and explicitly-disabled block both report disabled.
	assert.False(t, NewMergeQueueGenerator(&config.TrunkConfig{TrunkBranch: "main"}, "").Enabled())
	disabled := &config.TrunkConfig{MergeQueue: &config.MergeQueueConfig{Enabled: false}}
	assert.False(t, NewMergeQueueGenerator(disabled, "").Enabled())
}

func TestMergeQueueGenerator_TriggersAndPermissions(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch: "main",
		MergeQueue:  &config.MergeQueueConfig{Enabled: true},
	}
	gen := NewMergeQueueGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Triggered on merge_group (the lane behavior, distinct from the raw
	// trigger expressible under extra_triggers).
	assert.Contains(t, content, "name: Merge Queue Validation")
	assert.Contains(t, content, "on:\n  merge_group:")

	// Read-only: contents: read only, no write/release/deploy scopes.
	assert.Contains(t, content, "permissions:\n  contents: read\n")
	assert.NotContains(t, content, "contents: write")

	assert.Contains(t, content, "# AUTO-GENERATED by cascade")
}

func TestMergeQueueGenerator_Steps(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch: "main",
		MergeQueue:  &config.MergeQueueConfig{Enabled: true},
	}
	gen := NewMergeQueueGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Validate gate plus the dry-run orchestrate preview against the candidate.
	assert.Contains(t, content, "uses: actions/checkout@")
	assert.Contains(t, content, "uses: stablekernel/cascade/.github/actions/setup-cli@")
	assert.Contains(t, content, "cascade lint --json --config")
	assert.Contains(t, content, "cascade --dry-run orchestrate setup")

	// Validity gated on the parsed result.
	assert.Contains(t, content, "jq -r '.valid // false'")

	// No state/release/deploy side effects: the lane must not run finalize or
	// any publish/deploy operations.
	assert.NotContains(t, content, "orchestrate finalize")
	assert.NotContains(t, content, "generate-changelog")
	assert.NotContains(t, content, "action: publish")
}

// TestMergeQueueGenerator_DryRunResolvesEnvironment asserts that the preview
// dry-run step targets a concrete environment so version calculation succeeds.
//
// orchestrate setup looks the --environment value up in the manifest's
// environments list; an empty value resolves to no match and fails with
// `environment "" not found`. For a manifest that declares environments the
// preview must pass --environment with the first (lowest) environment, mirroring
// how the orchestrate workflow defaults its setup environment. For a manifest
// with no environments the flag must be omitted entirely.
func TestMergeQueueGenerator_DryRunResolvesEnvironment(t *testing.T) {
	t.Run("multi-env passes first environment", func(t *testing.T) {
		cfg := &config.TrunkConfig{
			TrunkBranch:  "main",
			Environments: config.EnvNames("staging", "prod"),
			MergeQueue:   &config.MergeQueueConfig{Enabled: true},
		}
		gen := NewMergeQueueGenerator(cfg, "")
		content, err := gen.Generate()
		require.NoError(t, err)

		previewBody := stepRunBody(t, content, "Preview Orchestration (dry-run)")
		assert.Contains(t, previewBody, "--environment staging",
			"preview dry-run must target the first environment so version calc succeeds")
		assert.NotContains(t, previewBody, "--environment \"\"",
			"preview dry-run must never pass an empty environment")
	})

	t.Run("no-env omits the environment flag", func(t *testing.T) {
		cfg := &config.TrunkConfig{
			TrunkBranch: "main",
			MergeQueue:  &config.MergeQueueConfig{Enabled: true},
		}
		gen := NewMergeQueueGenerator(cfg, "")
		content, err := gen.Generate()
		require.NoError(t, err)

		previewBody := stepRunBody(t, content, "Preview Orchestration (dry-run)")
		assert.NotContains(t, previewBody, "--environment",
			"no-env manifest must not pass --environment")
		assert.Contains(t, previewBody, "cascade --dry-run orchestrate setup")
	})
}

// TestMergeQueueGenerator_SetupCLIPassesToken asserts that the setup-cli step
// passes github.token so that gh release download can authenticate on a cold
// tool-cache. Without the token: input the composite action's GH_TOKEN is
// empty and gh exits non-zero.
func TestMergeQueueGenerator_SetupCLIPassesToken(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch: "main",
		MergeQueue:  &config.MergeQueueConfig{Enabled: true},
	}
	gen := NewMergeQueueGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "token: ${{ github.token }}",
		"setup-cli step must pass github.token so gh release download succeeds on a cold cache")
}

// TestMergeQueueGenerator_PinModeSHA confirms third-party action refs route
// through the shared pin helper rather than emitting a raw @v4.
func TestMergeQueueGenerator_PinModeSHA(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch: "main",
		PinMode:     config.PinModeSHA,
		MergeQueue:  &config.MergeQueueConfig{Enabled: true},
	}
	gen := NewMergeQueueGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0")
	assert.NotContains(t, content, "uses: actions/checkout@v4")
}

func TestMergeQueueGenerator_ValidYAML(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch: "main",
		MergeQueue:  &config.MergeQueueConfig{Enabled: true},
	}
	gen := NewMergeQueueGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	var parsed map[string]any
	require.NoError(t, yaml.Unmarshal([]byte(content), &parsed), "emitted workflow must be valid YAML")
	assert.Contains(t, parsed, "jobs")
	assert.Contains(t, parsed, "permissions")
}

// TestMergeQueueGeneratorE2E exercises the manifest -> parse -> generate path:
// an opted-in manifest yields a merge_group lane; omitting the block reports the
// generator disabled, so nothing is emitted.
func TestMergeQueueGeneratorE2E(t *testing.T) {
	tmpDir := t.TempDir()
	manifestPath := filepath.Join(tmpDir, "manifest.yaml")

	manifest := `ci:
  config:
    trunk_branch: main
    merge_queue:
      enabled: true
`
	require.NoError(t, os.WriteFile(manifestPath, []byte(manifest), 0644))

	cfg, err := config.ParseWithKey(manifestPath, "ci")
	require.NoError(t, err)

	gen := NewMergeQueueGenerator(cfg, tmpDir)
	require.True(t, gen.Enabled(), "opted-in manifest should enable the merge-queue lane")
	content, err := gen.Generate()
	require.NoError(t, err)
	assert.Contains(t, content, "on:\n  merge_group:")
	assert.Contains(t, content, "cascade --dry-run orchestrate setup")

	// Omitting the block is non-breaking: the generator reports disabled.
	bare := `ci:
  config:
    trunk_branch: main
`
	require.NoError(t, os.WriteFile(manifestPath, []byte(bare), 0644))
	bareCfg, err := config.ParseWithKey(manifestPath, "ci")
	require.NoError(t, err)
	assert.False(t, NewMergeQueueGenerator(bareCfg, tmpDir).Enabled(), "omitted block emits nothing")
}
