package generate

import (
	"fmt"
	"strings"

	"github.com/stablekernel/cascade/internal/config"
)

// prPreviewMarker is the hidden HTML marker embedded in the preview comment so a
// later run can find and update the same comment instead of posting a new one.
const prPreviewMarker = "<!-- cascade-pr-preview -->"

// PRPreviewGenerator emits the opt-in read-only PR plan-preview workflow (#40).
//
// The workflow runs on pull_request and is strictly read-only: it validates the
// manifest, detects which builds/deploys this merge would trigger against the PR
// diff, and dry-runs the applicable deploy callbacks, then writes a
// human-readable plan to $GITHUB_STEP_SUMMARY. When Comment is set it also
// posts (or updates) that plan as a PR comment via actions/github-script.
//
// dry_run is enforced (--dry-run is always passed, never sourced from an input)
// so the preview can never create a release, write state, or trigger a deploy.
type PRPreviewGenerator struct {
	config  *config.TrunkConfig
	baseDir string
}

// NewPRPreviewGenerator creates a new PR plan-preview workflow generator.
func NewPRPreviewGenerator(cfg *config.TrunkConfig, baseDir string) *PRPreviewGenerator {
	return &PRPreviewGenerator{
		config:  cfg,
		baseDir: baseDir,
	}
}

// getCLIRef returns the Git ref to use for the cascade actions.
func (g *PRPreviewGenerator) getCLIRef() string {
	version := g.config.GetCLIVersion()
	switch version {
	case "latest", "":
		return "latest"
	case "beta":
		return "master"
	default:
		return version
	}
}

// commentEnabled reports whether the preview should also post a PR comment.
func (g *PRPreviewGenerator) commentEnabled() bool {
	return g.config.PRPreview != nil && g.config.PRPreview.Comment
}

// Generate creates the PR plan-preview workflow content.
func (g *PRPreviewGenerator) Generate() (string, error) {
	if g.config.PRPreview == nil || !g.config.PRPreview.Enabled {
		return "", fmt.Errorf("cannot generate pr-preview workflow: pr_preview is not enabled")
	}

	var sb strings.Builder

	g.writeHeader(&sb)
	g.writeWorkflowTrigger(&sb)
	g.writePermissions(&sb)
	g.writeConcurrency(&sb)
	g.writeJob(&sb)

	return sb.String(), nil
}

func (g *PRPreviewGenerator) writeHeader(sb *strings.Builder) {
	sb.WriteString("# AUTO-GENERATED by cascade - DO NOT EDIT MANUALLY\n")
	fmt.Fprintf(sb, "# Regenerate with: cascade generate-workflow --config %s\n\n", g.config.GetManifestFile())
}

func (g *PRPreviewGenerator) writeWorkflowTrigger(sb *strings.Builder) {
	sb.WriteString("name: Cascade PR Preview\n\n")
	sb.WriteString("on:\n")
	sb.WriteString("  pull_request:\n")
}

// writePermissions emits least-privilege permissions. The preview only ever
// reads the repository; pull-requests: write is granted solely to post or update
// the plan comment, and only when commenting is enabled.
func (g *PRPreviewGenerator) writePermissions(sb *strings.Builder) {
	sb.WriteString("\npermissions:\n")
	sb.WriteString("  contents: read\n")
	if g.commentEnabled() {
		sb.WriteString("  pull-requests: write\n")
	}
}

// writeConcurrency serializes preview runs per pull request and cancels the
// in-flight run when the PR is updated, so only the latest diff's plan is shown.
func (g *PRPreviewGenerator) writeConcurrency(sb *strings.Builder) {
	sb.WriteString("\nconcurrency:\n")
	sb.WriteString("  group: \"cascade-pr-preview-${{ github.event.pull_request.number }}\"\n")
	sb.WriteString("  cancel-in-progress: true\n")
}

func (g *PRPreviewGenerator) writeJob(sb *strings.Builder) {
	sb.WriteString("\njobs:\n")
	sb.WriteString("  preview:\n")
	sb.WriteString("    name: Plan Preview\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    steps:\n")

	// Checkout the full history so detect-changes can diff base..head.
	writeActionStep(sb, g.config, "      ", actionCheckout)
	sb.WriteString("        with:\n")
	sb.WriteString("          fetch-depth: 0\n")
	sb.WriteString("\n")

	// Setup CLI.
	sb.WriteString("      - name: Setup CLI\n")
	fmt.Fprintf(sb, "        uses: stablekernel/cascade/.github/actions/setup-cli@%s\n", g.getCLIRef())
	sb.WriteString("        with:\n")
	fmt.Fprintf(sb, "          version: %s\n", g.config.GetCLIVersion())
	sb.WriteString("\n")

	g.writeValidateStep(sb)
	g.writeDetectStep(sb)
	g.writeDeployDryRunStep(sb)
	g.writePlanSummaryStep(sb)
	if g.commentEnabled() {
		g.writeCommentStep(sb)
	}
}

// writeValidateStep runs cascade parse-config as a required check. A malformed
// manifest exits non-zero here and fails the PR before merge.
func (g *PRPreviewGenerator) writeValidateStep(sb *strings.Builder) {
	sb.WriteString("      - name: Validate manifest\n")
	sb.WriteString("        run: |\n")
	fmt.Fprintf(sb, "          cascade parse-config --config %s\n", g.config.GetManifestFile())
	sb.WriteString("\n")
}

// writeDetectStep runs detect-changes against the PR diff (base..head). It is
// read-only and only reports which builds/deploys this merge would trigger.
func (g *PRPreviewGenerator) writeDetectStep(sb *strings.Builder) {
	sb.WriteString("      - name: Detect changes\n")
	// pull_request event fields are attacker-influenceable on a fork PR. GitHub
	// expands ${{ ... }} into the run: script before the shell parses it, so route
	// the SHAs through env: and reference them as quoted shell variables.
	sb.WriteString("        env:\n")
	sb.WriteString("          BASE_SHA: ${{ github.event.pull_request.base.sha }}\n")
	sb.WriteString("          HEAD_SHA: ${{ github.event.pull_request.head.sha }}\n")
	sb.WriteString("        run: |\n")
	sb.WriteString("          cascade detect-changes \\\n")
	fmt.Fprintf(sb, "            --config %s \\\n", g.config.GetManifestFile())
	sb.WriteString("            --base-sha \"$BASE_SHA\" \\\n")
	sb.WriteString("            --head-sha \"$HEAD_SHA\" \\\n")
	sb.WriteString("            > cascade-changes.json\n")
	sb.WriteString("\n")
}

// writeDeployDryRunStep computes the merge plan with the global --dry-run flag
// hard-coded, so no release is cut, no state is written, and no deploy is
// triggered. orchestrate setup only reports the head SHA, the version that would
// be cut, and which builds/deploys this merge would run.
func (g *PRPreviewGenerator) writeDeployDryRunStep(sb *strings.Builder) {
	sb.WriteString("      - name: Compute plan (dry-run)\n")
	// pull_request.head.sha is attacker-influenceable on a fork PR; route it
	// through env: rather than interpolating it into the run: script.
	sb.WriteString("        env:\n")
	sb.WriteString("          HEAD_SHA: ${{ github.event.pull_request.head.sha }}\n")
	sb.WriteString("        run: |\n")
	sb.WriteString("          # READ-ONLY: --dry-run is enforced and never sourced from an input,\n")
	sb.WriteString("          # so no release is cut, no state is written, and no deploy is triggered.\n")
	sb.WriteString("          cascade --dry-run orchestrate setup \\\n")
	fmt.Fprintf(sb, "            --config %s \\\n", g.config.GetManifestFile())
	sb.WriteString("            --sha \"$HEAD_SHA\" \\\n")
	sb.WriteString("            > cascade-plan.json\n")
	sb.WriteString("\n")
}

// writePlanSummaryStep renders the human-readable plan to $GITHUB_STEP_SUMMARY
// and stashes it in a step output for the optional comment step.
func (g *PRPreviewGenerator) writePlanSummaryStep(sb *strings.Builder) {
	sb.WriteString("      - name: Write plan summary\n")
	sb.WriteString("        id: summary\n")
	sb.WriteString("        run: |\n")
	sb.WriteString("          builds=\"$(jq -r '[.run_builds // {} | to_entries[] | select(.value) | .key] | join(\", \")' cascade-plan.json)\"\n")
	sb.WriteString("          deploys=\"$(jq -r '[.run_deploys // {} | to_entries[] | select(.value != \"false\") | .key] | join(\", \")' cascade-plan.json)\"\n")
	sb.WriteString("          version=\"$(jq -r '.version // \"\"' cascade-plan.json)\"\n")
	sb.WriteString("          {\n")
	sb.WriteString("            echo '## Cascade plan preview'\n")
	sb.WriteString("            echo ''\n")
	sb.WriteString("            echo 'This merge would:'\n")
	sb.WriteString("            if [ -n \"$builds\" ]; then echo \"- Build: $builds\"; fi\n")
	sb.WriteString("            if [ -n \"$deploys\" ]; then echo \"- Deploy: $deploys\"; fi\n")
	sb.WriteString("            if [ -n \"$version\" ]; then echo \"- Cut version: $version\"; fi\n")
	sb.WriteString("            if [ -z \"$builds\" ] && [ -z \"$deploys\" ]; then\n")
	sb.WriteString("              echo '- No build or deploy would be triggered by this merge.'\n")
	sb.WriteString("            fi\n")
	sb.WriteString("          } > cascade-summary.md\n")
	sb.WriteString("          cat cascade-summary.md >> \"$GITHUB_STEP_SUMMARY\"\n")
	if g.commentEnabled() {
		sb.WriteString("          {\n")
		sb.WriteString("            echo 'body<<CASCADE_EOF'\n")
		sb.WriteString("            cat cascade-summary.md\n")
		sb.WriteString("            echo 'CASCADE_EOF'\n")
		sb.WriteString("          } >> \"$GITHUB_OUTPUT\"\n")
	}
	sb.WriteString("\n")
}

// writeCommentStep posts or updates the plan as a PR comment. It finds a prior
// cascade comment by its hidden marker and edits it in place so the PR carries a
// single, always-current plan rather than a new comment per push.
func (g *PRPreviewGenerator) writeCommentStep(sb *strings.Builder) {
	sb.WriteString("      - name: Post plan comment\n")
	writeActionUses(sb, g.config, "        ", actionGithubScript)
	sb.WriteString("        with:\n")
	sb.WriteString("          script: |\n")
	fmt.Fprintf(sb, "            const marker = '%s';\n", prPreviewMarker)
	sb.WriteString("            const body = marker + '\\n' + `${{ steps.summary.outputs.body }}`;\n")
	sb.WriteString("            const { owner, repo } = context.repo;\n")
	sb.WriteString("            const issue_number = context.payload.pull_request.number;\n")
	sb.WriteString("            const comments = await github.paginate(github.rest.issues.listComments, {\n")
	sb.WriteString("              owner, repo, issue_number,\n")
	sb.WriteString("            });\n")
	sb.WriteString("            const existing = comments.find((c) => c.body && c.body.includes(marker));\n")
	sb.WriteString("            if (existing) {\n")
	sb.WriteString("              await github.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });\n")
	sb.WriteString("            } else {\n")
	sb.WriteString("              await github.rest.issues.createComment({ owner, repo, issue_number, body });\n")
	sb.WriteString("            }\n")
}
