package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stablekernel/cascade/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func prPreviewConfig(comment bool) *config.TrunkConfig {
	return &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev"},
		PRPreview: &config.PRPreviewConfig{
			Enabled: true,
			Comment: comment,
		},
	}
}

// TestPRPreviewGenerator_PRFieldsAreNotInterpolatedIntoRun asserts that the
// pull_request event fields the preview workflow consumes (head/base SHAs) are
// not substituted directly into a run: shell body. Although these are SHAs, the
// values originate from the pull_request event, which is attacker-influenceable
// on a fork PR, so they are routed through env: like every other untrusted input.
func TestPRPreviewGenerator_PRFieldsAreNotInterpolatedIntoRun(t *testing.T) {
	gen := NewPRPreviewGenerator(prPreviewConfig(false), "")
	content, err := gen.Generate()
	require.NoError(t, err)

	detectBody := stepRunBody(t, content, "Detect changes")
	assert.NotContains(t, detectBody, "${{ github.event.",
		"detect-changes run: body must not interpolate pull_request event fields")
	assert.Contains(t, detectBody, "--base-sha \"$BASE_SHA\"")
	assert.Contains(t, detectBody, "--head-sha \"$HEAD_SHA\"")

	planBody := stepRunBody(t, content, "Compute plan (dry-run)")
	assert.NotContains(t, planBody, "${{ github.event.",
		"plan dry-run run: body must not interpolate pull_request event fields")
	assert.Contains(t, planBody, "--sha \"$HEAD_SHA\"")

	// Values bound via step env:.
	assert.Contains(t, content, "BASE_SHA: ${{ github.event.pull_request.base.sha }}")
	assert.Contains(t, content, "HEAD_SHA: ${{ github.event.pull_request.head.sha }}")
}

// TestPRPreviewGenerator_DryRunResolvesEnvironment asserts that the plan
// dry-run step targets a concrete environment so version calculation succeeds.
//
// orchestrate setup looks the --environment value up in the manifest's
// environments list; an empty value resolves to no match and fails with
// `environment "" not found`. For a manifest that declares environments the
// preview must pass --environment with the first (lowest) environment, mirroring
// how the orchestrate workflow defaults its setup environment. For a manifest
// with no environments the flag must be omitted entirely.
func TestPRPreviewGenerator_DryRunResolvesEnvironment(t *testing.T) {
	t.Run("multi-env passes first environment", func(t *testing.T) {
		cfg := prPreviewConfig(false)
		cfg.Environments = []string{"staging", "prod"}

		gen := NewPRPreviewGenerator(cfg, "")
		content, err := gen.Generate()
		require.NoError(t, err)

		planBody := stepRunBody(t, content, "Compute plan (dry-run)")
		assert.Contains(t, planBody, "--environment staging",
			"plan dry-run must target the first environment so version calc succeeds")
		assert.NotContains(t, planBody, "--environment \"\"",
			"plan dry-run must never pass an empty environment")
	})

	t.Run("no-env omits the environment flag", func(t *testing.T) {
		cfg := prPreviewConfig(false)
		cfg.Environments = nil

		gen := NewPRPreviewGenerator(cfg, "")
		content, err := gen.Generate()
		require.NoError(t, err)

		planBody := stepRunBody(t, content, "Compute plan (dry-run)")
		assert.NotContains(t, planBody, "--environment",
			"no-env manifest must not pass --environment")
		assert.Contains(t, planBody, "cascade --dry-run orchestrate setup")
	})
}

func TestPRPreviewGenerator_Disabled(t *testing.T) {
	// nil pr_preview
	gen := NewPRPreviewGenerator(&config.TrunkConfig{TrunkBranch: "main"}, "")
	_, err := gen.Generate()
	require.Error(t, err)

	// enabled: false
	gen = NewPRPreviewGenerator(&config.TrunkConfig{
		TrunkBranch: "main",
		PRPreview:   &config.PRPreviewConfig{Enabled: false},
	}, "")
	_, err = gen.Generate()
	require.Error(t, err)
}

func TestPRPreviewGenerator_Enabled(t *testing.T) {
	gen := NewPRPreviewGenerator(prPreviewConfig(false), "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Header + name.
	assert.Contains(t, content, "# AUTO-GENERATED by cascade")
	assert.Contains(t, content, "name: Cascade PR Preview")

	// Triggered on pull_request.
	assert.Contains(t, content, "on:\n  pull_request:")

	// Read-only permissions; no pull-requests: write when not commenting.
	assert.Contains(t, content, "permissions:\n  contents: read\n")
	assert.NotContains(t, content, "pull-requests: write")

	// The three read-only steps.
	assert.Contains(t, content, "cascade parse-config")
	assert.Contains(t, content, "cascade detect-changes")
	assert.Contains(t, content, "cascade --dry-run orchestrate setup")

	// Change detection runs against the PR diff (base..head). The SHAs are bound
	// to env: and passed as quoted shell variables, never interpolated into run:.
	assert.Contains(t, content, "--base-sha \"$BASE_SHA\"")
	assert.Contains(t, content, "--head-sha \"$HEAD_SHA\"")

	// Plan written to the step summary.
	assert.Contains(t, content, "$GITHUB_STEP_SUMMARY")
	assert.Contains(t, content, "## Cascade plan preview")
	assert.Contains(t, content, "This merge would:")

	// No comment step when commenting is disabled.
	assert.NotContains(t, content, "actions/github-script")
}

func TestPRPreviewGenerator_DryRunEnforced(t *testing.T) {
	gen := NewPRPreviewGenerator(prPreviewConfig(true), "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// --dry-run is hard-coded on the plan computation.
	assert.Contains(t, content, "cascade --dry-run orchestrate setup")

	// dry_run is never sourced from a workflow input, and there are no inputs
	// at all on the pull_request trigger that could override it.
	assert.NotContains(t, content, "inputs.dry_run")
	assert.NotContains(t, content, "workflow_dispatch")

	// No write-bearing operations: no release, no state write, no deploy.
	assert.NotContains(t, content, "cascade orchestrate finalize")
	assert.NotContains(t, content, "cascade external update")
}

func TestPRPreviewGenerator_CommentAddsScriptAndPermission(t *testing.T) {
	gen := NewPRPreviewGenerator(prPreviewConfig(true), "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// pull-requests: write is granted only for commenting.
	assert.Contains(t, content, "permissions:\n  contents: read\n  pull-requests: write\n")

	// github-script step posts/updates the comment.
	assert.Contains(t, content, "Post plan comment")
	assert.Contains(t, content, "actions/github-script")
	assert.Contains(t, content, "cascade-pr-preview") // hidden marker for update-in-place
	assert.Contains(t, content, "updateComment")
	assert.Contains(t, content, "createComment")
}

func TestPRPreviewGenerator_ActionRefsPinUnderSHAMode(t *testing.T) {
	cfg := prPreviewConfig(true)
	cfg.PinMode = config.PinModeSHA

	gen := NewPRPreviewGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// checkout and github-script must route through the pin helper and emit
	// SHAs (with the trailing version comment) under sha mode.
	checkout := defaultActionPins[actionCheckout]
	script := defaultActionPins[actionGithubScript]
	assert.Contains(t, content, "actions/checkout@"+checkout.sha+" # "+checkout.shaVersion)
	assert.Contains(t, content, "actions/github-script@"+script.sha+" # "+script.shaVersion)

	// No bare major-tag refs for these actions under sha mode.
	assert.NotContains(t, content, "actions/checkout@v4\n")
	assert.NotContains(t, content, "actions/github-script@v7\n")
}

func TestPRPreviewGenerator_ValidYAML(t *testing.T) {
	gen := NewPRPreviewGenerator(prPreviewConfig(true), "")
	content, err := gen.Generate()
	require.NoError(t, err)

	var parsed map[string]any
	require.NoError(t, yaml.Unmarshal([]byte(content), &parsed), "generated workflow must be valid YAML")

	// Indentation must be a multiple of two spaces.
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, " ") {
			trimmed := strings.TrimLeft(line, " ")
			spaces := len(line) - len(trimmed)
			assert.True(t, spaces%2 == 0, "indentation should be a multiple of 2: %q", line)
		}
	}
}

// TestRunGenerateWorkflow_PRPreview is a generator-level e2e: a manifest with
// pr_preview.enabled is generated and the preview workflow file lands on disk
// with the expected content. A manifest without pr_preview emits nothing.
func TestRunGenerateWorkflow_PRPreview(t *testing.T) {
	const previewManifest = `ci:
  config:
    project: test-project
    trunk_branch: main
    environments: [dev]
    pr_preview:
      enabled: true
      comment: true
    builds:
      - name: app
        workflow: .github/workflows/build.yaml
        triggers: ["src/**"]
`

	tmpDir := t.TempDir()

	configPath := filepath.Join(tmpDir, "manifest.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(previewManifest), 0644))

	workflowDir := filepath.Join(tmpDir, ".github/workflows")
	require.NoError(t, os.MkdirAll(workflowDir, 0755))
	buildWorkflow := "name: Build\non:\n  workflow_call:\n    outputs:\n      image_tag:\n        value: test\n"
	require.NoError(t, os.WriteFile(filepath.Join(workflowDir, "build.yaml"), []byte(buildWorkflow), 0644))

	outputPath := filepath.Join(workflowDir, "orchestrate.yaml")
	opts := defaultOpts(configPath, outputPath)
	opts.force = true
	t.Cleanup(func() { _ = os.Remove(filepath.Join(".github/workflows", "cascade-rollback.yaml")) })
	require.NoError(t, runGenerateWorkflow(opts))

	previewPath := filepath.Join(".github/workflows", "cascade-pr-preview.yaml")
	t.Cleanup(func() { _ = os.Remove(previewPath) })

	raw, err := os.ReadFile(previewPath)
	require.NoError(t, err, "preview workflow should be generated")
	content := string(raw)
	assert.Contains(t, content, "name: Cascade PR Preview")
	assert.Contains(t, content, "on:\n  pull_request:")
	assert.Contains(t, content, "cascade parse-config")
	assert.Contains(t, content, "pull-requests: write")
	assert.Contains(t, content, "actions/github-script")
}

func TestRunGenerateWorkflow_NoPRPreviewWhenAbsent(t *testing.T) {
	tmpDir := t.TempDir()

	configPath := filepath.Join(tmpDir, "manifest.yaml")
	require.NoError(t, os.WriteFile(configPath, []byte(validManifestContent), 0644))

	workflowDir := filepath.Join(tmpDir, ".github/workflows")
	require.NoError(t, os.MkdirAll(workflowDir, 0755))
	buildWorkflow := "name: Build\non:\n  workflow_call:\n    outputs:\n      image_tag:\n        value: test\n"
	require.NoError(t, os.WriteFile(filepath.Join(workflowDir, "build.yaml"), []byte(buildWorkflow), 0644))

	outputPath := filepath.Join(workflowDir, "orchestrate.yaml")
	opts := defaultOpts(configPath, outputPath)
	opts.force = true
	t.Cleanup(func() { _ = os.Remove(filepath.Join(".github/workflows", "cascade-rollback.yaml")) })
	require.NoError(t, runGenerateWorkflow(opts))

	previewPath := filepath.Join(".github/workflows", "cascade-pr-preview.yaml")
	t.Cleanup(func() { _ = os.Remove(previewPath) })

	_, err := os.Stat(previewPath)
	assert.True(t, os.IsNotExist(err), "no preview workflow should be emitted when pr_preview is absent")
}
