package generate

import (
	"strings"
	"testing"

	"github.com/stablekernel/cascade/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestReleaseGenerator_NoRollbackJob documents the rollback-parity decision: the
// release workflow tags, generates the changelog, and publishes a GitHub release.
// It performs no environment deploy, so there is no deploy to auto-roll-back
// (unlike promote/hotfix). The generated workflow must therefore name no rollback
// job at all.
func TestReleaseGenerator_NoRollbackJob(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	for _, line := range strings.Split(content, "\n") {
		assert.NotContains(t, strings.ToLower(line), "rollback",
			"release workflow must not emit any rollback job or step")
	}
}

func TestReleaseGenerator_Generate(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify header
	assert.Contains(t, content, "# AUTO-GENERATED by cascade")
	assert.Contains(t, content, "name: Release")

	// Verify environment documentation
	assert.Contains(t, content, "# Environment: prod")

	// Verify release actions documented
	assert.Contains(t, content, "create-draft")
	assert.Contains(t, content, "prerelease")
	assert.Contains(t, content, "release")

	// Verify jobs exist
	assert.Contains(t, content, "  preflight:")
	assert.Contains(t, content, "  release:")
	assert.Contains(t, content, "  finalize:")

	// Verify breaking change gate
	assert.Contains(t, content, "allow_breaking_changes")
	assert.Contains(t, content, "Check Breaking Changes")
}

func TestReleaseGenerator_ReleaseActions(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"dev"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify all release actions are in options
	assert.Contains(t, content, "          - create-draft")
	assert.Contains(t, content, "          - prerelease")
	assert.Contains(t, content, "          - release")

	// Verify default is create-draft
	assert.Contains(t, content, "default: create-draft")

	// Verify each action has a conditional step
	assert.Contains(t, content, "release_action == 'create-draft'")
	assert.Contains(t, content, "release_action == 'prerelease'")
	assert.Contains(t, content, "release_action == 'release'")
}

func TestReleaseGenerator_ValidYAML(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Basic YAML structure checks
	assert.Contains(t, content, "name: Release\n\non:")
	assert.Contains(t, content, "on:\n  workflow_dispatch:")
	assert.Contains(t, content, "jobs:\n  preflight:")

	// Check indentation is consistent (2 spaces)
	lines := strings.Split(content, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, " ") {
			// Count leading spaces
			trimmed := strings.TrimLeft(line, " ")
			spaces := len(line) - len(trimmed)
			assert.True(t, spaces%2 == 0, "Indentation should be multiples of 2: %q", line)
		}
	}
}

func TestReleaseGenerator_LatestReleaseStateUpdate(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify latest_release state update
	assert.Contains(t, content, "Update Latest Release State")
	assert.Contains(t, content, ".latest_release.version")
	assert.Contains(t, content, ".latest_release.sha")
	assert.Contains(t, content, ".latest_release.released_on")
	assert.Contains(t, content, ".latest_release.released_by")
	assert.Contains(t, content, "github.triggering_actor")

	// Should only update on actual release (not draft or prerelease)
	assert.Contains(t, content, "release_action == 'release'")
}

// TestReleaseGenerator_LatestReleaseStateUpdate_PushRetriesOnConflict mirrors
// the orchestrate finalize fix from #101: a concurrent run pushing state can
// race with this step's plain `git push`, producing a non-fast-forward error
// and a failed release. The fix wraps the yq edits + commit + push in a
// fetch+reset+reapply+push retry loop, so the slower run rebuilds its commit
// on the latest tip and pushes as a clean fast-forward.
func TestReleaseGenerator_LatestReleaseStateUpdate_PushRetriesOnConflict(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Extract the Update Latest Release State step body for focused assertions.
	updateIdx := strings.Index(content, "- name: Update Latest Release State")
	require.GreaterOrEqual(t, updateIdx, 0, "Update Latest Release State step missing")
	step := content[updateIdx:]
	if next := strings.Index(step[1:], "- name:"); next > 0 {
		step = step[:next+1]
	}

	// Must rebase off the latest remote tip before pushing.
	assert.Contains(t, step, "git fetch", "step must fetch before push")
	// Must retry on rejection (single push is the bug we're fixing).
	assert.Regexp(t, `(?i)attempt|retry|for `, step, "step must retry on push rejection")
	// Re-apply yq edits inside the loop to avoid rebase conflicts on the
	// same yaml line.
	assert.Contains(t, step, "git reset --hard", "retry loop must reset to remote tip before re-applying state")
	// Final attempt must fail loudly so a real problem still surfaces.
	assert.Regexp(t, `(?s)exit\s+1`, step, "loop must exit non-zero after exhausting retries")
}

func TestReleaseGenerator_DryRunSupport(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify dry run input exists
	assert.Contains(t, content, "dry_run:")
	assert.Contains(t, content, "type: boolean")

	// Verify dry run condition on release job
	assert.Contains(t, content, "if: ${{ github.event.inputs.dry_run != 'true' }}")
}

func TestReleaseGenerator_SemverTagCalculation(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify semver tag calculation
	assert.Contains(t, content, "Calculate Semver Tag")
	assert.Contains(t, content, "semver_tag")
	assert.Contains(t, content, "sed 's/-rc\\.[0-9]*$//'")

}

// TestReleaseGenerator_SemverTagCalculation_CustomToken proves the emitted strip
// pattern follows the configured tag grammar: a beta token with an empty
// separator yields the beta-shaped sed expression, not the rc one.
func TestReleaseGenerator_SemverTagCalculation_CustomToken(t *testing.T) {
	betaToken := "beta"
	emptySep := ""
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
		TagGrammar: &config.TagGrammarConfig{
			PreReleaseToken:     &betaToken,
			PreReleaseSeparator: &emptySep,
		},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "sed 's/-beta[0-9]*$//'")
	assert.NotContains(t, content, "sed 's/-rc\\.[0-9]*$//'")
}

func TestReleaseGenerator_ChangelogGeneration(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify changelog generation
	assert.Contains(t, content, "Generate Changelog")
	assert.Contains(t, content, "cascade generate-changelog")
	assert.Contains(t, content, ".latest_release.sha")
}

func TestReleaseGenerator_Summary(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify summary step
	assert.Contains(t, content, "name: Summary")
	assert.Contains(t, content, "## Release Complete")
	assert.Contains(t, content, "GITHUB_STEP_SUMMARY")
}

func TestReleaseGenerator_UsesCorrectActions(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify it uses the local manage-release action
	assert.Contains(t, content, "./.github/actions/manage-release")
	assert.Contains(t, content, "action: update")
	assert.Contains(t, content, "action: prerelease")
	assert.Contains(t, content, "action: publish")
}

func TestReleaseGenerator_WithCLIVersion(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
		CLIVersion:   "v1.0.0",
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Verify CLI version is used in setup-cli action
	assert.Contains(t, content, "setup-cli@v1.0.0")
	assert.Contains(t, content, "version: v1.0.0")
}

// TestReleaseGenerator_HasConcurrencyBlock asserts the generated release workflow
// declares a top-level concurrency: block keyed by the bare workflow name. Release
// runs write the shared GitHub Releases surface and shared tags, so ALL release runs
// race regardless of release_action (#31); the group must serialize every release
// run, not just same-action runs. cancel-in-progress is false because a
// partially-executed release action may already have pushed a tag that a cancelled
// run leaves dangling.
func TestReleaseGenerator_HasConcurrencyBlock(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "\nconcurrency:\n", "release workflow must declare top-level concurrency:")
	group := concurrencyGroupLine(t, content)
	assert.Equal(t, "  group: \"${{ github.workflow }}\"", group, "release concurrency group must be the bare workflow name to serialize all runs")
	assert.NotContains(t, group, "release_action", "release concurrency group must NOT scope by action: different actions still touch the same releases/tags")
	assert.Contains(t, content, "cancel-in-progress: false", "release default must queue, not cancel")
}

// TestReleaseGenerator_ConcurrencyOverride asserts that a manifest-level
// concurrency config is forwarded to the generated release workflow.
func TestReleaseGenerator_ConcurrencyOverride(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:  "main",
		Environments: []string{"prod"},
		Concurrency: &config.ConcurrencyConfig{
			Group:            "my-custom-release",
			CancelInProgress: true,
		},
	}

	gen := NewReleaseGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "group: my-custom-release", "custom group must propagate to release")
	assert.Contains(t, content, "cancel-in-progress: true", "custom cancel_in_progress must propagate to release")
}

func TestReleaseGenerator_AllowBreakingChanges_BakesGateOff(t *testing.T) {
	// Default: the breaking-change gate reads the per-run workflow input.
	def := &config.TrunkConfig{TrunkBranch: "main", Environments: []string{"prod"}}
	defContent, err := NewReleaseGenerator(def, "").Generate()
	require.NoError(t, err)
	assert.Contains(t, defContent, "ALLOW_BREAKING: ${{ github.event.inputs.allow_breaking_changes }}\n")
	assert.NotContains(t, defContent, "ALLOW_BREAKING: \"true\"\n")

	// allow_breaking_changes: true bakes the gate off so a breaking release
	// proceeds even when the per-run input is unchecked.
	on := &config.TrunkConfig{TrunkBranch: "main", Environments: []string{"prod"}, AllowBreakingChanges: true}
	onContent, err := NewReleaseGenerator(on, "").Generate()
	require.NoError(t, err)
	assert.Contains(t, onContent, "ALLOW_BREAKING: \"true\"\n")
	assert.NotContains(t, onContent, "ALLOW_BREAKING: ${{ github.event.inputs.allow_breaking_changes }}\n")
	// The operator-facing input stays declared; the gate simply no longer
	// depends on it.
	assert.Contains(t, onContent, "allow_breaking_changes:\n")
}
