package generate

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/stablekernel/cascade/internal/config"
)

// RollbackGenerator emits the cascade-rollback workflow. The workflow re-deploys
// a prior version or SHA to an environment: a read-only preflight job resolves
// the target, one deploy job per configured deployable re-runs the deploy keyed
// on the resolved SHA, and a finalize job applies the state write back to trunk
// (marking the environment diverged until a forward promotion rejoins it).
//
// The deploy stage reuses the same deploy callbacks (reusable-workflow, or
// matrix) the promote workflow drives; there is no separate rollback deploy
// path. The generator is gated on the configured environment count: it
// emits only when at least one environment is declared.
type RollbackGenerator struct {
	config  *config.TrunkConfig
	baseDir string
}

// NewRollbackGenerator creates a rollback-workflow generator bound to the given
// trunk config and repository base directory.
func NewRollbackGenerator(cfg *config.TrunkConfig, baseDir string) *RollbackGenerator {
	return &RollbackGenerator{
		config:  cfg,
		baseDir: baseDir,
	}
}

// Enabled reports whether the rollback workflow should be emitted. It is emitted
// when the manifest declares at least one environment, since a rollback re-points
// an environment at a prior deployment.
func (g *RollbackGenerator) Enabled() bool {
	return g.config != nil && len(g.config.Environments) >= 1
}

// getCLIRef mirrors the ref-resolution used by the other generators so the
// emitted setup-cli ref tracks config.cli_version. "beta" is the explicit opt-in
// escape hatch to the "master" branch; everything else resolves through
// GetCLIVersion (which pins "" / "latest" to the immutable default).
func (g *RollbackGenerator) getCLIRef() string {
	if g.config.CLIVersion == "beta" {
		return "master" // Explicit opt-in escape hatch to trunk.
	}
	return g.config.GetCLIVersion()
}

// getReleaseTokenRef returns the token expression for deploy/release operations.
func (g *RollbackGenerator) getReleaseTokenRef() string {
	return g.config.GetReleaseToken()
}

// getStateTokenRef returns the token expression used to write manifest state to
// the trunk branch.
func (g *RollbackGenerator) getStateTokenRef() string {
	return g.config.GetStateToken()
}

// getManifestFilePath returns the repo-relative manifest path for use in the
// generated workflow, matching the other generators' resolution.
func (g *RollbackGenerator) getManifestFilePath() string {
	manifestPath := g.config.GetManifestFile()
	if !filepath.IsAbs(manifestPath) {
		return manifestPath
	}
	if g.baseDir != "" {
		if rel, err := filepath.Rel(g.baseDir, manifestPath); err == nil {
			return rel
		}
	}
	return ".github/manifest.yaml"
}

// Generate renders the cascade-rollback workflow.
func (g *RollbackGenerator) Generate() (string, error) {
	var sb strings.Builder

	g.writeHeader(&sb)
	g.writeTriggers(&sb)
	g.writeConcurrency(&sb)
	g.writeJobs(&sb)

	return sb.String(), nil
}

func (g *RollbackGenerator) writeHeader(sb *strings.Builder) {
	sb.WriteString("# AUTO-GENERATED by cascade - DO NOT EDIT MANUALLY\n")
	fmt.Fprintf(sb, "# Regenerate with: cascade generate-workflow --config %s\n", g.getManifestFilePath())
	sb.WriteString("#\n")
	sb.WriteString("# Manual rollback: re-deploy a prior version or SHA to an environment.\n")
	sb.WriteString("#\n")
	sb.WriteString("# A read-only preflight resolves the target (from live state, the\n")
	sb.WriteString("# deploy-history ring, or manifest history), the deploy stage re-runs the\n")
	sb.WriteString("# configured deploy callbacks keyed on the resolved SHA, and finalize writes\n")
	sb.WriteString("# the rolled-back state back to trunk, marking the environment diverged until\n")
	sb.WriteString("# a forward promotion rejoins it.\n")
	sb.WriteString("\n")
}

func (g *RollbackGenerator) writeTriggers(sb *strings.Builder) {
	sb.WriteString("name: Rollback\n\n")
	sb.WriteString("on:\n")
	sb.WriteString("  workflow_dispatch:\n")
	sb.WriteString("    inputs:\n")

	// environment: enumerate the configured environments as a choice so the
	// operator picks from the declared set rather than free-typing.
	sb.WriteString("      environment:\n")
	sb.WriteString("        description: 'Environment to roll back'\n")
	sb.WriteString("        required: true\n")
	sb.WriteString("        type: choice\n")
	sb.WriteString("        options:\n")
	for _, env := range g.config.Environments {
		fmt.Fprintf(sb, "          - %s\n", env)
	}

	sb.WriteString("      target:\n")
	sb.WriteString("        description: 'Prior version or SHA (optional; defaults to the previous version)'\n")
	sb.WriteString("        required: false\n")
	sb.WriteString("        type: string\n")
	sb.WriteString("        default: ''\n")

	sb.WriteString("      deployable:\n")
	sb.WriteString("        description: 'Limit rollback to one deployable (optional)'\n")
	sb.WriteString("        required: false\n")
	sb.WriteString("        type: string\n")
	sb.WriteString("        default: ''\n")

	sb.WriteString("      dry_run:\n")
	sb.WriteString("        description: 'Resolve and print without deploying'\n")
	sb.WriteString("        required: false\n")
	sb.WriteString("        type: boolean\n")
	sb.WriteString("        default: false\n")
	sb.WriteString("\n")

	// Base: contents:write to commit the rolled-back state; actions:write for
	// parity with the promote workflow's release/dispatch surface. A reusable
	// callback cannot set its own job permissions, so any scope a deploy callback
	// declares (e.g. id-token: write for OIDC) is unioned in at the top level
	// here.
	base := [][2]string{
		{"contents", "write"},
		{"actions", "write"},
	}
	writeTopLevelPermissions(sb, base, collectCallbackPermissions(g.config))
}

// writeConcurrency serializes rollback runs so concurrent state writes cannot
// interleave. The default group keys on the workflow; an explicit config group
// overrides it, mirroring the promote generator.
func (g *RollbackGenerator) writeConcurrency(sb *strings.Builder) {
	sb.WriteString("concurrency:\n")
	if g.config.Concurrency != nil && g.config.Concurrency.Group != "" {
		fmt.Fprintf(sb, "  group: %s\n", g.config.Concurrency.Group)
	} else {
		sb.WriteString("  group: \"${{ github.workflow }}\"\n")
	}
	if g.config.Concurrency != nil {
		fmt.Fprintf(sb, "  cancel-in-progress: %t\n", g.config.Concurrency.CancelInProgress)
	} else {
		sb.WriteString("  cancel-in-progress: false\n")
	}
	sb.WriteString("\n")
}

func (g *RollbackGenerator) writeJobs(sb *strings.Builder) {
	sb.WriteString("jobs:\n")
	g.writePreflightJob(sb)
	g.writeDeployJobs(sb)
	g.writeFinalizeJob(sb)
}

// writeSetupCLI emits the checkout + setup-cli steps shared by the rollback jobs.
func (g *RollbackGenerator) writeSetupCLI(sb *strings.Builder) {
	writeActionStep(sb, g.config, "      ", actionCheckout)
	sb.WriteString("        with:\n")
	sb.WriteString("          fetch-depth: 0\n")
	sb.WriteString("      - name: Setup CLI\n")
	fmt.Fprintf(sb, "        uses: stablekernel/cascade/.github/actions/setup-cli@%s\n", g.getCLIRef())
	sb.WriteString("        with:\n")
	fmt.Fprintf(sb, "          token: %s\n", g.getReleaseTokenRef())
	fmt.Fprintf(sb, "          version: %s\n", g.config.GetCLIVersion())
}

// writePreflightJob emits the read-only target-resolution job. It exposes the
// resolved environment, SHA, version, and can_proceed gate as outputs for the
// deploy and finalize jobs, and fails fast when resolution reports it cannot
// proceed.
func (g *RollbackGenerator) writePreflightJob(sb *strings.Builder) {
	sb.WriteString("  preflight:\n")
	sb.WriteString("    name: Pre-flight Check\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    outputs:\n")
	sb.WriteString("      target_env: ${{ steps.preflight.outputs.target_env }}\n")
	sb.WriteString("      target_sha: ${{ steps.preflight.outputs.target_sha }}\n")
	sb.WriteString("      target_version: ${{ steps.preflight.outputs.target_version }}\n")
	sb.WriteString("      can_proceed: ${{ steps.preflight.outputs.can_proceed }}\n")
	sb.WriteString("    steps:\n")
	g.writeSetupCLI(sb)

	sb.WriteString("      - name: Resolve Target\n")
	sb.WriteString("        id: preflight\n")
	sb.WriteString("        env:\n")
	sb.WriteString("          ENVIRONMENT: ${{ github.event.inputs.environment }}\n")
	sb.WriteString("          TARGET: ${{ github.event.inputs.target }}\n")
	sb.WriteString("          DEPLOYABLE: ${{ github.event.inputs.deployable }}\n")
	sb.WriteString("        run: |\n")
	sb.WriteString("          cascade rollback preflight \\\n")
	fmt.Fprintf(sb, "            --config %s \\\n", g.getManifestFilePath())
	sb.WriteString("            --env \"$ENVIRONMENT\" \\\n")
	sb.WriteString("            --to \"$TARGET\" \\\n")
	sb.WriteString("            --deployable \"$DEPLOYABLE\" \\\n")
	sb.WriteString("            --gha-output\n")

	sb.WriteString("      - name: Fail if Cannot Proceed\n")
	sb.WriteString("        if: steps.preflight.outputs.can_proceed == 'false'\n")
	sb.WriteString("        run: exit 1\n")
	sb.WriteString("\n")
}

// rollbackDeployGuard is the if-condition gating a rollback deploy job: not a
// dry run, and either no deployable filter or a filter naming this deployable.
func rollbackDeployGuard(deployName string) string {
	return fmt.Sprintf("${{ github.event.inputs.dry_run != 'true' && (github.event.inputs.deployable == '' || github.event.inputs.deployable == '%s') }}", deployName)
}

// writeDeployJobs emits one deploy job per configured deploy, re-running the same
// callback the promote workflow uses but sourced from the resolved rollback
// target SHA. Each deploy is a reusable (uses:) workflow call that threads the
// resolved env and SHA via the with: input. With no environments configured, no
// deploy jobs emit.
func (g *RollbackGenerator) writeDeployJobs(sb *strings.Builder) {
	if len(g.config.Environments) == 0 {
		return
	}

	for _, d := range g.config.Deploys {
		fmt.Fprintf(sb, "  deploy-%s:\n", d.Name)
		fmt.Fprintf(sb, "    name: Deploy %s\n", d.Name)
		sb.WriteString("    needs: [preflight]\n")
		fmt.Fprintf(sb, "    if: %s\n", rollbackDeployGuard(d.Name))

		// Reusable (uses:) deploy: thread the resolved env and SHA via with:. The
		// environment name is carried as an input; GitHub Environment protection
		// must be declared inside the reusable workflow's own job.
		fmt.Fprintf(sb, "    uses: %s\n", normalizeWorkflowPath(d.Workflow))
		sb.WriteString("    with:\n")
		sb.WriteString("      environment: ${{ needs.preflight.outputs.target_env }}\n")
		sb.WriteString("      sha: ${{ needs.preflight.outputs.target_sha }}\n")
		writeSecretsBlock(sb, d.Secrets)
	}
}

// deployJobNames returns the deploy job identifiers so finalize can declare
// correct needs: references.
func (g *RollbackGenerator) deployJobNames() []string {
	names := make([]string, 0, len(g.config.Deploys))
	for _, d := range g.config.Deploys {
		names = append(names, "deploy-"+d.Name)
	}
	return names
}

// writeFinalizeJob emits the state-write job. It runs after preflight succeeds
// (and after every deploy job), skipping on a dry run, and re-resolves the target
// deterministically via the passed-through SHA before applying and committing.
//
// The job condition uses always() so finalize still runs when a deploy job
// fails or is skipped: finalize must observe every deploy result to decide
// whether the state write is safe. Each deploy's conclusion is threaded in as a
// DEPLOY_RESULT_<NAME> env var, and the CLI aborts the state write (leaving
// trunk unchanged) when an in-scope deploy did not succeed. always() guarantees
// finalize reaches that gate rather than being skipped by a failed dependency.
func (g *RollbackGenerator) writeFinalizeJob(sb *strings.Builder) {
	needsList := append([]string{"preflight"}, g.deployJobNames()...)
	needsStr := "[" + strings.Join(needsList, ", ") + "]"

	sb.WriteString("  finalize:\n")
	sb.WriteString("    name: Finalize\n")
	fmt.Fprintf(sb, "    needs: %s\n", needsStr)
	sb.WriteString("    if: always() && needs.preflight.result == 'success' && github.event.inputs.dry_run != 'true'\n")
	sb.WriteString("    runs-on: ubuntu-latest\n")
	sb.WriteString("    steps:\n")
	g.writeSetupCLI(sb)

	sb.WriteString("      - name: Finalize Rollback\n")
	sb.WriteString("        env:\n")
	fmt.Fprintf(sb, "          GH_TOKEN: %s\n", g.getStateTokenRef())
	fmt.Fprintf(sb, "          GITHUB_TOKEN: %s\n", g.getReleaseTokenRef())
	sb.WriteString("          GITHUB_REPOSITORY: ${{ github.repository }}\n")
	// Thread the dispatch deployable scope through so finalize applies and gates
	// at the same scope the deploy jobs ran at. An empty value is env-scope, the
	// same default the CLI flag carries, so a full-env rollback still mirrors and
	// marks the env diverged while a deployable-scoped rollback touches only that
	// deployable. Without this, a deployable-scoped dispatch would resolve and
	// deploy one deployable but finalize the whole environment.
	sb.WriteString("          DEPLOYABLE: ${{ github.event.inputs.deployable }}\n")
	// Thread each deploy job's conclusion in as DEPLOY_RESULT_<NAME> so the CLI
	// can gate the state write on actual deploy success. Deploy jobs only exist
	// when at least one environment is configured.
	if len(g.config.Environments) > 0 {
		for _, d := range g.config.Deploys {
			envKey := "DEPLOY_RESULT_" + strings.ToUpper(strings.ReplaceAll(d.Name, "-", "_"))
			fmt.Fprintf(sb, "          %s: ${{ needs.deploy-%s.result }}\n", envKey, d.Name)
		}
	}
	sb.WriteString("        run: |\n")
	sb.WriteString("          cascade rollback finalize \\\n")
	fmt.Fprintf(sb, "            --config %s \\\n", g.getManifestFilePath())
	sb.WriteString("            --env \"${{ needs.preflight.outputs.target_env }}\" \\\n")
	sb.WriteString("            --to \"${{ needs.preflight.outputs.target_sha }}\" \\\n")
	sb.WriteString("            --deployable \"$DEPLOYABLE\" \\\n")
	sb.WriteString("            --commit-push\n")
}
