package generate

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stablekernel/cascade/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestValidateCheckGenerator_Enabled(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:   "main",
		ValidateCheck: &config.ValidateCheckConfig{Enabled: true},
	}
	gen := NewValidateCheckGenerator(cfg, "")
	assert.True(t, gen.Enabled(), "validate_check.enabled should report enabled")

	// Absent block and explicitly-disabled block both report disabled.
	assert.False(t, NewValidateCheckGenerator(&config.TrunkConfig{TrunkBranch: "main"}, "").Enabled())
	disabled := &config.TrunkConfig{ValidateCheck: &config.ValidateCheckConfig{Enabled: false}}
	assert.False(t, NewValidateCheckGenerator(disabled, "").Enabled())
}

func TestValidateCheckGenerator_TriggersAndPermissions(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:   "main",
		ValidateCheck: &config.ValidateCheckConfig{Enabled: true},
	}
	gen := NewValidateCheckGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Triggered on pull_request.
	assert.Contains(t, content, "name: Validate Manifest")
	assert.Contains(t, content, "on:\n  pull_request:")

	// Least-privilege: contents: read only, no write scopes.
	assert.Contains(t, content, "permissions:\n  contents: read\n")
	assert.NotContains(t, content, "contents: write")

	// Auto-generated banner.
	assert.Contains(t, content, "# AUTO-GENERATED by cascade")
}

func TestValidateCheckGenerator_Steps(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:   "main",
		ValidateCheck: &config.ValidateCheckConfig{Enabled: true},
	}
	gen := NewValidateCheckGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	// Checkout + setup-cli + the parse-config validity gate.
	assert.Contains(t, content, "uses: actions/checkout@")
	assert.Contains(t, content, "uses: stablekernel/cascade/.github/actions/setup-cli@")
	assert.Contains(t, content, "cascade parse-config --config")

	// parse-config reports validity in JSON (valid: false), not via exit code,
	// so the workflow must gate on the parsed result.
	assert.Contains(t, content, "jq -r '.valid // false'")
	assert.Contains(t, content, "exit 1")

	// No dry-run callbacks or comment side effects (that is the plan-preview
	// issue, intentionally not part of this fast validity gate).
	assert.NotContains(t, content, "--dry-run")
	assert.NotContains(t, content, "createComment")
}

// TestValidateCheckGenerator_SetupCLIPassesToken asserts that the setup-cli
// step passes github.token so that gh release download can authenticate on a
// cold tool-cache. Without the token: input the composite action's GH_TOKEN is
// empty and gh exits non-zero.
func TestValidateCheckGenerator_SetupCLIPassesToken(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:   "main",
		ValidateCheck: &config.ValidateCheckConfig{Enabled: true},
	}
	gen := NewValidateCheckGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "token: ${{ github.token }}",
		"setup-cli step must pass github.token so gh release download succeeds on a cold cache")
}

// TestValidateCheckGenerator_PinModeSHA confirms third-party action refs route
// through the shared pin helper rather than emitting a raw @v4.
func TestValidateCheckGenerator_PinModeSHA(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:   "main",
		PinMode:       config.PinModeSHA,
		ValidateCheck: &config.ValidateCheckConfig{Enabled: true},
	}
	gen := NewValidateCheckGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	assert.Contains(t, content, "uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10")
	assert.NotContains(t, content, "uses: actions/checkout@v4")
}

func TestValidateCheckGenerator_ValidYAML(t *testing.T) {
	cfg := &config.TrunkConfig{
		TrunkBranch:   "main",
		ValidateCheck: &config.ValidateCheckConfig{Enabled: true},
	}
	gen := NewValidateCheckGenerator(cfg, "")
	content, err := gen.Generate()
	require.NoError(t, err)

	var parsed map[string]any
	require.NoError(t, yaml.Unmarshal([]byte(content), &parsed), "emitted workflow must be valid YAML")
	assert.Contains(t, parsed, "jobs")
	assert.Contains(t, parsed, "permissions")
}

// TestValidateCheckGeneratorE2E exercises the manifest -> parse -> generate path
// the CLI uses: an opted-in manifest yields a pull_request validation workflow;
// the same manifest with the block omitted reports the generator disabled, so
// nothing is emitted.
func TestValidateCheckGeneratorE2E(t *testing.T) {
	tmpDir := t.TempDir()
	manifestPath := filepath.Join(tmpDir, "manifest.yaml")

	manifest := `ci:
  config:
    trunk_branch: main
    validate_check:
      enabled: true
`
	require.NoError(t, os.WriteFile(manifestPath, []byte(manifest), 0644))

	cfg, err := config.ParseWithKey(manifestPath, "ci")
	require.NoError(t, err)

	gen := NewValidateCheckGenerator(cfg, tmpDir)
	require.True(t, gen.Enabled(), "opted-in manifest should enable the validate check")
	content, err := gen.Generate()
	require.NoError(t, err)
	assert.Contains(t, content, "on:\n  pull_request:")
	assert.Contains(t, content, "cascade parse-config")

	// Omitting the block is non-breaking: the generator reports disabled.
	bare := `ci:
  config:
    trunk_branch: main
`
	require.NoError(t, os.WriteFile(manifestPath, []byte(bare), 0644))
	bareCfg, err := config.ParseWithKey(manifestPath, "ci")
	require.NoError(t, err)
	assert.False(t, NewValidateCheckGenerator(bareCfg, tmpDir).Enabled(), "omitted block emits nothing")
}
